### ISSUE TITLE
Trix issues from the sponsor -surge- screencasts

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1040]
As requested by @calebporzio I am posting my thoughts on the Trix lesson.
https://github.com/livewire/surge/commit/ce6cf4e313b80edca551649e1584fed9187f9cca

There are more comments on the commit + a temporary AlpineJS solution, while waiting for a "proper" solution.

**Issues:**

1. Trix blur before Submit.
The user must click outside of the trix editor field or hit tab before the form submit is clicked, otherwise Livewire does not pick up on the change event.
The user will not know that the update is not saved unless he/she manually reloads the page (which they don’t).

2. If the field value is changed in backend the Trix field is not updated when Livewire redraws the component.

**Comment by stevebauman** [comment]
Experiencing issues like this with Trix as well... ☹️

**Comment by tanthammar** [comment]
Yes it would really be nice to get a solution on how to solve situations like this. At the moment I am submitting the form via Alpine to avoid the issue.

**Comment by stevebauman** [comment]
Yeah -- admittedly, I'm removing Livewire from the project I was working on. I'm honestly not enough of a JavaScript expert to dig into these issues and don't have enough time to troubleshoot.

Unpoly is looking more and more promising (I'll be writing a blog post about it!). It focuses on straight up server side rendering as much as possible (which I love). It provides full reactivity to pages by simply adding HTML attributes.

Hoping for a bit more support here on the issue repository -- but for now I simply can't implement Livewire due some of these issues and it conflicting with other libraries.

**Comment by tanthammar** [comment]
@stevebauman please keep me posted. I played around with https://htmx.org/, blazin fast and super easy to implement. But I was unable to use inline `<script>` tags in blade files that are injected. (something I do a lot in blade components, - yes, might not be a good practice but I do it anyway) 

Can you dm me on twitter, lets not pollute the issue tracker with our chatter :)
https://twitter.com/TinaHammar

**Comment by roni-estein** [comment]
Just a quick question, I’d ask why you think something like pushing a script onto a stack is bad practice from a blade component? As long as you are only pushing it once.
  

  
Since these will all be browser cached after the first request on a device. I’ve started using livewire alpine in production level apps. And I may have a unique situation where hundreds of people (limited only staff) are getting these bits but they are on the servers all day long and it’s not having any impact at all.
  

  
I think only on this part of your issue you might be over engineering a bit. Something we all do. But lately I’m forcing myself to just go with it until it presents a problem and I’ve probably saved my clients thousands of dollars not spinning wheels solving problems we don’t actually have.
  

  
Just a bit of encouragement, do what feels good, and let the problems guide you. Instead of pre-solving.
  

  
Have a super day.
  

  
  
  

  
  
>

**Comment by stevebauman** [comment]
Hi @tanthammar! I'm not able to DM you on Twitter, says this for some reason:

<img width="618" alt="Screen Shot 2020-06-21 at 9 21 07 PM" src="https://user-images.githubusercontent.com/6421846/85240185-3083c680-b405-11ea-8a9f-d1e79d87568e.png">

Send me a DM when you're free! https://twitter.com/stevbauman

I'm really interested to hear what your dev workflow looks like and what tools you use. I think we're in a similar stage right now (looking for ways to speed up productivity being a lone devs).

@roni-estein 

> Just a quick question, I’d ask why you think something like pushing a script onto a stack is bad practice from a blade component? As long as you are only pushing it once.

I feel like it's pushed against in the Laravel community a bit. There's also a sense of "dirtiness" I feel when I do it this way, but this feeling isn't warranted by actual evidence of it being bad practice. I guess when I open my blade files I don't expect to see JavaScript inside, as it's kind of outside the bounds of where you would traditionally look (inside your `resources/js/app.js`).

Just my two cents!

**Comment by tanthammar** [comment]
Can bump this issue, it's been a while and I have yet to find another solution.

**Comment by tanthammar** [comment]
Closing this issue, because it is resolved with the v2 `@entangle('propertyName').defer` directive.
