### ISSUE TITLE
Application key not defined

### ISSUE THREAD

**Issue by Wulfheart** [livewire/livewire#1218]
### Description

When clicking multiple times in a row on a button there is a server error, that  no encryption key has been specified.

I'm sure, that I have specified one as the site loads correctly.

#### Context
- Livewire version: 1.3.0
- Laravel version: 7.18.0
- Browser: Firefox

#### Instructions
- Get the repo at https://github.com/Wulfheart/weird-livewire.
- ``composer install``
- ``npm install``
- Do whatever you do to run a server. 🧙‍♂️
- Navigate to the root page of the site (``/``).
- Click on ``Random gradient`` multiple(n > 20) times really fast.
- After some clicks there will be a server error displayed.

**Comment by MrWeb** [comment]
This is not happening with me (Chrome) and I think you shuold use a form with a submit button instead of a button with `wire:click="randomGradient"` so that the form gets disabled on submit and reenabled once the function is over.

![ezgif-4-ff0e05265bde](https://user-images.githubusercontent.com/4120466/86573806-2de0af80-bf75-11ea-8fab-b7ff619c645e.gif)
