### ISSUE TITLE
Listening for Events without Echo

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#1472]
Is it currently possible to listen to events without them using broadcasting and https://laravel-livewire.com/docs/laravel-echo?

I've tried a few things with `Event::listen` like creating a listener in the `mount` method and calling a local method but Livewire seems to lose track of the event listener because it works a few times but then just stops.

**Comment by nuernbergerA** [comment]
Some time ago I was working on a PoC for this with [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) but dropped it because then you would have to change stuff with your server configuration and so on to handle long-running responses.

But if anyone shows up and what to work on this I'm happy to share my knowledge.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
