### ISSUE TITLE
Storage Exceeds Quota

### ISSUE THREAD

**Issue by ItsANameToo** [livewire/livewire#1631]
### Description

Since the upgrade to Livewire 2, I've been running into the `"Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '<random string>' exceeded the quota."` error when refreshing a page during testing. Looking at the session storage, it is filling up with the same data on each refresh until it no longer fits and runs into the above error. Manually clearing the session storage resolve the issue, but only temporary as ~10 page refreshes later I run into it again. 

Issue is similar to https://github.com/livewire/livewire/issues/1586 but it does not clean up older entries for me as suggested there

### Exact steps to reproduce

- Have a livewire component for which data is stored in the session storage.
- Refresh the page and see entries getting added to session storage
- Refresh until session storage runs out of space

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.4.0
- Browser: Chrome

**Comment by calebporzio** [comment]
Hi @ItsANameToo,

I've tried to reproduce this and am having trouble.

I'm perplexed that this is really happening on version 2.2.3

Please test this in an incognito window and verify this is still happening.

If it is, please re-open/re-submit this issue with more explicit instructions on how to reproduce this - preferably copy-pastable code snippets so others can reproduce.

Thanks!

**Comment by ItsANameToo** [comment]
@calebporzio the same issue occurs in an incognito tab. I find it difficult to reproduce the issue in a simple code snippet, as I'm unsure what triggers livewire to store something in session storage. Do you have any pointers that explain when livewire resorts to using session storage?

**Comment by calebporzio** [comment]
Ah yes, the $queryString property is one

**Comment by deanzod** [comment]
@calebporzio  I can confirm the same behaviour on 2.2.3 also. It does take a LOT of refreshes (or actions) but eventually the app stops working due to the error message and the only way to fix it is to clear session storage in dev tools. I can get this to happen every time with around 100 refreshes.

Seems like it fills sessions storage, if you delete an entry and refresh it is ok but the next refresh will be full again. Need some way to maybe set a session storage limit / purge after x new requests?

**Comment by deanzod** [comment]
@calebporzio ok, I've just been testing this a bit more:

On my app if I open a brand new tab, login with new session, completely clean session storage I was refreshing forever and all seemed to be working ok and removing old session entries after a certain point.

If I log out, then log back in, and keep refreshing the error appears and session storage is full. So what I think is happening is because the session storage doesn't clear when you log out, those entries are kind of orphaned and new entries are just appended attached to the new session perhaps with the limit set back to a whole 5mb even though the previous session may have already taken up 4.5mb

**Comment by deanzod** [comment]
Steps to reproduce:

Create new livewire component and use $queryString (just any random variable - doesn't even need to be in the view).
In the view add a huge amount of text. I used this 1mb text for my test:

https://gist.github.com/khaykov/a6105154becce4c0530da38e723c2330

This allowed me to refresh the page 3 times before hitting the limit and getting the error.

**Comment by ItsANameToo** [comment]
@deanzod thanks for the reproduction, I'll take a look at re-publishing the assets to see if it also solves the problem for me
