### ISSUE TITLE
wire:click not works on <a> or <div> tags

### ISSUE THREAD

**Issue by michele-grifa** [livewire/livewire#1638]
### Description
In my component view if you want to listen for click event on **div** or **a** tags, but the event is not triggered

### Exact steps to reproduce
- Add wire:click on a **div** or **a** tag
- Click on the tag and nothing happens

### Stripped-down, copy-pastable code snippets
`
<a class='item' x-ref='item' wire:click="clickedLink()">
    //Some text
</a>
`

**Context**
- Livewire version: 2.2.5
- Laravel version: 8.3.1
- Browser: Firefox

**Comment by michele-grifa** [comment]
Sorry, I forgot to mention that the **a** tag is dynamically generated after component creation

**Comment by allmanaj** [comment]
Hey! Ah yeah, that'll make all the difference!

If they're being dynamically generated by alpine (just a guess due to the `x-ref`) then you'll want to use `x-on:click="$wire.clickedLink()"` as opposed to `wire:click`. This is because you these items are loaded after your livewire component's finished rendering and so it cannot add an event listener to them because they weren't there when it was creating its event listeners.

If they are being generated by livewire then they should work fine with `wire:click`!

you can see an example [here](https://laravelplayground.com/#/snippets/949133de-dfe5-4d53-9ba3-a798cc6b9bb8)

**Comment by michele-grifa** [comment]
Thanks it worked
