### ISSUE TITLE
Saving user model not really works when scout & algolia is active

### ISSUE THREAD

**Issue by dylanmichaelryan** [livewire/livewire#1639]
### Description
I had the problem that after installing Scout & Algolia I could no longer edit my users properly.

Every few save operations an error occurred:

`cURL error 28: Resolving timed out after 2070 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

### Exact steps to reproduce
1. Install new Laravel 8 Application
2. Install Livewire
3. Install & setup scout & algoliasearch-client-php
4. Run migrations for user model
5. copy paste code from belove to a livewire component

### Stripped-down, copy-pastable code snippets
User Model
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Scout\Searchable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, Searchable;

    protected $fillable = [
        'name', 'email', 'password',
    ];
}

```

Component Class
```
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class Test extends Component
{
    public User $user;

    protected $rules = [
        'user.name' => ['required'],
        'user.email' => ['required', 'email:rfc,dns'],
    ];

    public function save()
    {
        $this->validate();

        $this->user->save();
    }
}

```

Component view
```
<div>
    <input type="text" wire:model.lazy="user.name">
    <input type="text" wire:model.lazy="user.email">
    <button type="button" wire:click="save">Save user data</button>
</div>
```

Route
```
Route::get('/user/{user}', \App\Http\Livewire\Test::class);
```

Sometimes it saves, and sometimes it throws the error, theres like a 50/50 change it works.

-> Removing `use Searchable;` from the User model fixed the issue for me

**Context**
- Livewire version: [e.g. 2.2.5]
- Laravel version: [e.g. 8.3.1]
- Browser: Chrome & Safari - probably others aswell

**Comment by iksaku** [comment]
Just for the record, while using Laravel Scout, any models implementing the `Searchable` trait also updates its searching records on update. This behaviour is [described in Scout's documentation](https://laravel.com/docs/8.x/scout#updating-records).

Since you're using Livewire to update your models, your timeout must be due to the sum of:
1. Latency to the server.
2. Time save in your DB.
3. Latency from your server to Algolia's.
4. Time for Algolia to process the update request and return a response.
5. Time for your server to process Algolia's response and return a Livewire response.

As you described, the total timeout reported is for `2070 milliseconds`, which roughly means it is a `2.07 seconds` timeout. Livewire may be expecting responses in a shorter span.

By removing the `Searchable` trait from your model, you're effectively removing the time it takes for your server to negotiate model updates with Algolia, so, your process time is reduced greatly.

As [described in Scout's docs](https://laravel.com/docs/8.x/scout#pausing-indexing), you can actually prepare your model for an update **without** sending it to Algolia directly. This will impact the time-to-updated of your search data in Algolia, but will effectively reduce the time it takes to process your Livewire's requests.

As a *temporal* fix, you could send your models to an "update search data" queue, so it is done in the background.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
