### ISSUE TITLE
@entangle used with a simple array does not seem to work.  

### ISSUE THREAD

**Issue by isaackearl** [livewire/livewire#1682]
### Description
I was trying to use entangle to keep track of a simple array on both the livewire and alpine side, but though I can get the initial value, no changes to the javascript array ever appear to make a change to the php (livewire) array.  No requests go to the backend etc.  I would expect each change to the javascript array to produce a network request that would update the public properties (arrays) and then re-render the dom..  

### Exact steps to reproduce

Here is a laravelplayground livewire script showing what I am talking about:

This is a really simple one
https://laravelplayground.com/#/snippets/38ba0f3a-9f43-4d41-9be1-6661330f1e93

Here is one where I sort of got it to work by using a method on the php side via $wire.methodname, but it just exposed another issue related to trying to work with arrays.  (it's adding 2 entries when it clearly should be adding 1).  It does the same thing if I use wire:click directly.  Also this defeats the purpose of what I'm trying to do by using alpine to give the user a smoother experience and then entangle variables to have the backend updated lazily.
https://laravelplayground.com/#/snippets/d0898465-4019-44b7-a247-4b5320a249eb

this is a slightly less simple one but still simple overall
https://laravelplayground.com/#/snippets/18e267aa-1e2e-4fcf-9302-59a3fd0808ef

Essentially it initially reads the values of the array just fine when it first "entangles" but any changes don't result in an update to livewire.  If you console.log the resulting javascript object, instead of an array, it is a Proxy().  I understand that's how this feature works, but for primitive values etc when you console.log them it shows the actual value...  

Are arrays just not supported?  Is there some other way I can do this that would work?  Does a collection work where a simple array does not?

### Stripped-down, copy-pastable code snippets

see laravelplayground.com link...

**Context**
- Livewire version: v2.2.6
- Laravel version: v8.6.0
- Browser: any

**Comment by isaackearl** [comment]
I've confirmed this still affects v2.2.7.  Also: using $wire.set('someArray', myArray) etc also doesn't work, if you are changing the values that are already there.  I always get this error when trying to modify public property livewire arrays with an array from alpine (whether it is entangled or not)
```
Livewire encountered corrupt data when trying to hydrate the [dual-list-box] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
```

**Comment by isaackearl** [comment]
Added a few simpler examples of issues (multiple issues)

**Comment by calebporzio** [comment]
Thanks for the thorough issue posting and submitting the Laravel Playground link. HUGE HELP.

I've fixed this issue: https://github.com/livewire/livewire/commit/19df71ac14525b93c147ee42fd6f667c857681d5

Will be available in the next release.

For context: the issue is because when using @entangle, Alpine was actually storing an exact reference to Livewire's array, so when Alpine mutated the array, it triggered the watcher, but checked to see that the values were different before sending the update to Laravel. Because both values are the same, it just skipped the Livewire update. I'm now deep cloning @entangle values so Alpine and Livewire references never get crossed.

Thanks again.

If there's another issue contained in this thread, please re-submit in a separate issue and reference here. Thanks!

**Comment by Slowwie** [comment]
Is it possible that [this](https://github.com/livewire/livewire/discussions/1750) is a related problem? 

It happens to me - I am on version 2.2.9

First I thought - I was wrong doing changes to the state with alpine instead of using $wire.addSubject() for example. 
But when I see this examples of @isaackearl - it should work just fine when I change the initial array of values. 

So this might noch be solved yet. Or hopefully I did a mistake :D

**Comment by AdamEsterle** [comment]
This may be broken again with Livewire 3. I am having issues with @entangle and arrays
