### ISSUE TITLE
Not preserving validation errors between actions

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#1739]
In latest version of livewire, validation errors are being reset when an action is triggered.

How do I stop this for a specific action?

For example, I have a form with buttons to add input rows. If I submit the form and there are validation errors I see them, but when I click the "add input row" button the validation errors are all gone.

**Comment by boptom** [comment]
I believe this is due to this change in [v2.2.4](https://github.com/livewire/livewire/releases/tag/v2.2.4):
- Only persist error bag validation errors for component properties, not from custom validators

As far as I'm aware the only way to persist the validation errors is to use corresponding public properties.

**Comment by calebporzio** [comment]
Yes, the update in v2.2.4 DID change this behavior because it was considered buggy behavior.

The gist is: when using your own validators, you DONT want them to persist, and now Livewire matches that behavior.

Thanks for chiming in @boptom 

If you DO want them to persist, you will need a public property for the validation key.

(If you feel there's more that Livewire can offer when it comes to persisting validation errors, please re-submit an issue with more source code and reasons behind the suggestion)

Thanks!
