### ISSUE TITLE
Manually creating validators with keys that do not match public class properties cannot be tested

### ISSUE THREAD

**Issue by boptom** [livewire/livewire#1740]
### Description
Manually creating validators with keys that do not match public class properties cannot be tested with Livewire test methods. This is required when the public properties of a Livewire component does not match that of a model which needs updating.

The Livewire component validator works as expected, however, the test methods do not.

Note: This bug is not present in v2.2.3. It occurs in v2.2.4 and up due to the change of:
- Only persist error bag validation errors for component properties, not from custom validators: [#1398](https://github.com/livewire/livewire/pull/1398)

### Exact steps to reproduce
- Install Laravel and Livewire.
- Create the component and test file outlined below.
- Run the test.

```
laravel new lwtest
cd lwtest
composer require livewire/livewire
php artisan livewire:make LiveComponent
php artisan make:test LiveComponentTest
```

### Stripped-down, copy-pastable code snippets

Livewire Component:
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Facades\Validator;

class LiveComponent extends Component
{
    public $requiredProp;

    public function submit()
    {
        Validator::make([
            'changePropKey' => $this->requiredProp,
        ], [
            'changePropKey' => 'required',
        ])->validate();
    }
}
```

The test code which is expected to pass:
```php
<?php

namespace Tests\Feature;

use App\Http\Livewire\LiveComponent;
use Livewire\Livewire;
use Tests\TestCase;

class LiveComponentTest extends TestCase
{
    /** @test */
    public function test_component()
    {
        Livewire::test(LiveComponent::class)
            ->set('requiredProp', null)
            ->call('submit')
            ->assertHasErrors();
    }
}
```

The test output:
```
1) Tests\Feature\LiveComponentTest::test_component
Component has no errors.
Failed asserting that false is true.
```

Note: if the validator keys match the public properties (as below), the test passes:
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Facades\Validator;

class LiveComponent extends Component
{
    public $requiredProp;

    public function submit()
    {
        Validator::make([
            'requiredProp' => $this->requiredProp,
        ], [
            'requiredProp' => 'required',
        ])->validate();
    }
}
```

**Context**
- Livewire version: 2.2.4 and higher
- Laravel version: 8.0.3
- Browser: any

**Comment by daraghoshea** [comment]
I'm having similar issues to this, and it's caused a lot of tests that used `assertHasError()` to now fail.

**Background**

I have an `AssessmentIndex` component that renders a paginated list view for an `Assessment` model. 

Each rendered list item has a button that calls a `startReport($modelId)` action method on the `AssessmentIndex` component.

The `startReport()` throws a `ValidationException::withMessages(['report' => 'Report cannot be started'])` based on a business logic check. 

In tests, I check to make sure the business logic works by checking `assertHasErrors('report')`. Prior to version `2.2.4` this worked fine.

Now, the test fails because `report` is not a public property on the `AssessmentIndex` component, so is not available to `assertHasErrors()`.

**Context**

* Livewire: `v2.2.9`
* Laravel: `v8.9`

**Comment by daraghoshea** [comment]
I've found a bigger testing problem, due to copying the approach taken in `Jetstream`, for example [`TeamMemberManager` component](https://github.com/laravel/jetstream/blob/1.x/src/Http/Livewire/TeamMemberManager.php).

The approach here is to keep the form variables in an array on the component:

```php


    /**
     * The "add team member" form state.
     *
     * @var array
     */
    public $addTeamMemberForm = [
        'email' => '',
        'role' => null,
    ];
```

which is used in the blade template like:

```html
                   <!-- Member Email -->
                   <div class="col-span-6 sm:col-span-4">
                        <x-jet-label for="email" value="{{ __('Email') }}" />
                        <x-jet-input id="name" type="text" class="mt-1 block w-full" wire:model.defer="addTeamMemberForm.email" />
                        <x-jet-input-error for="email" class="mt-2" />
                    </div>
```

The method on the component that is called to add a team member looks like:

```php
/**
     * Add a new team member to a team.
     *
     * @param  \Laravel\Jetstream\Contracts\AddsTeamMembers
     * @return void
     */
    public function addTeamMember(AddsTeamMembers $adder)
    {
        $this->resetErrorBag();

        $adder->add(
            $this->user,
            $this->team,
            $this->addTeamMemberForm['email'],
            $this->addTeamMemberForm['role']
        );

        $this->addTeamMemberForm = [
            'email' => '',
            'role' => null,
        ];

        $this->team = $this->team->fresh();

        $this->emit('saved');
    }

```

The `AddsTeamMembers` class that is injected in the method, validates the `email` and `role` like this:

``` php
Validator::make([
            'email' => $email,
            'role' => $role,
        ], $this->rules(), [
            'email.exists' => __('We were unable to find a registered user with this email address.'),
        ])->after(
            $this->ensureUserIsNotAlreadyOnTeam($team, $email)
        )->validateWithBag('addTeamMember');
```

### Problem

The component works as expected, and returns an error message when validation does not pass.
As above, the Member email input is wired to `addTeamMemberForm.email` and expects an errorBag property of `email`.

This works as expected during the render: 
![image](https://user-images.githubusercontent.com/1172998/95679749-d3d33400-0bcc-11eb-8bfe-5c51a25c39d0.png)


The problem is that this cannot be tested.

``` php
/** @test **/
    function can_add_a_team_member()
    {
        \Gate::policy(Team::class, TeamPolicy::class);
        Jetstream::useUserModel(User::class);
        Jetstream::role('admin', 'Admin', ['foo']);

        $team = $this->createTeam();

        $otherUser = User::forceCreate([
            'name' => 'Adam Wathan',
            'email' => 'adam@laravel.com',
            'password' => 'secret',
        ]);

        Livewire::actingAs($team->owner)
            ->test('teams.team-member-manager', ['team' => $team])
            ->set('addTeamMemberForm.email', '')
            ->set('addTeamMemberForm.role', 'admin')
            ->call('addTeamMember')
            ->assertHasErrors('email');
    }
```

When this is run, the component does not have any errors for `email`:

```
Component has no errors.
Failed asserting that false is true.
```

As mentioned, this is due to the change for 2.2.4:

* Only persist error bag validation errors for component properties, not from custom validators: #1398

**Comment by daraghoshea** [comment]
For anyone reading, I've adopted a new approach to deal with the above problem in copying the `Jetstream` approach.

Now I have a unit test that tests the functionality of the `Action` method, and the `Livewire` component tests just check to make sure that the correct parameters are passed through to the `Action` method using a Mockery spy.

This is arguably a better design, so the lack of validation errors isn't an issue any more.

I'm now undecided on whether it's a problem that you cannot access validation errors that are not a public property on the component.

In the other issue, I solved the problem of not having the validation error in the `assertError()` method by instead checking to see if an event is emitted `assertEmitted() / assertNotEmitted()` instead.

I haven't personally run into the issue that caused the change in #1398, so I assume the tradeoffs are known and understood, and that this approach is worth the issue of the missing Validation errors.

**Comment by mattharcourt** [comment]
Maybe we've encountered a nuance of Livewire not fully captured by testing utilities.

A test like `Livewire::test('foo')->call('bar')->assertHasErrors()` will be checking for errors that survive Livewire's dehydrate/hydrate cycle which is important for component property errors in order for `validateOnly()` to work as expected. If not for `validateOnly()` no errors would need to persist beyond when they are used in the Blade view during `render()` (as is the case in Laravel).

Maybe what is needed is an `assertViewHas()` and/or `assertViewHasError()` testing method to verify that appropriate data is available in the view.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
