### ISSUE TITLE
How to configure livewire upload with dropzone ?

### ISSUE THREAD

**Issue by shankhadevpadam** [livewire/livewire#1799]
How to configure livewire upload with dropzone?

**Comment by zepfietje** [comment]
@shankhadevpadam, please discuss this type of question in the "Discussions" tab, forum or community Discord instead of opening an issue (unless you're running into some sort of Livewire bug). In this case, you could even just have checked out the docs: https://laravel-livewire.com/docs/2.x/file-uploads#js-api. Please close this issue.

**Comment by shankhadevpadam** [comment]
Ok thanks.
