### ISSUE TITLE
@entangle causes x-init to happen multiple times

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1850]
When I have `@entangle` on my alpine components, their `x-init` happens every time I change the value. I don't think that's expected right?
In some cases it doesn't introduce bugs, but sometimes I do heavy things on init, and sometimes really bad bugs are introduced because of this, like when you initialize a rich text editor multiple times every time you type a character.

**Comment by jonneroelofs** [comment]
I think when you are using 3rd party javascript libraries that effect the DOM you want to use wire:ignore . For example:
![image](https://user-images.githubusercontent.com/20800818/96590341-2fe13b00-12e6-11eb-8d28-adf7a3840181.png)

Also:
https://laravel-livewire.com/docs/2.x/alpine-js (check out the last paragraph)

**Comment by mokhosh** [comment]
Actually, I do have `wire:ignore`.
That works with `wire:model` and rerendering the DOM, but doesn't have any effect on `x-init` being run multiple times when you have `@entangle`

**Comment by jonneroelofs** [comment]
I also have it I see. Seems to happen on my end because the component is shown conditionally.
When I show the component unconditionally x-init is not called multiple times in my case.

**Comment by mokhosh** [comment]
I have it unconditionally.

I did use it inside an `@if` before, but that created too many problems and now I'm just `x-show`ing it within another `@entangle`d alpine component.
So, no conditionals here.

**Comment by iksaku** [comment]
@mokhosh Could you try replicating this issue in a [Playground](https://laravelplayground.com/)? that way we could trace the issue easier.

**Comment by mokhosh** [comment]
Sure, here:
https://laravelplayground.com/#/snippets/d377a67f-89c6-4b2e-b9e3-45bb36f81976

As you can see 1) the is no conditional 2) there is `wire:ignore` on the child 3) there is a `div` with `wire:ignore` wrapping the child for extra safety. But it still `init`s when you change the input.

**Comment by iksaku** [comment]
I see the issue now, however, if you're going to be using `@entangle` with AlpineJS and you're technically not using it.

From the example you gave, you're using `@entangle` in the root Alpine element, and you're also creating an empty child Alpine element that doesn't take advantage of this:
```blade
<div x-data="{ name: @entangle('name') }">
    <div x-data>
        <input wire:model="name" />
    </div>
    <!-- Other data -->
</div>
```

The main reason for you to use `@entangle` is to be able to proxy the value of a Livewire property into AlpineJS for an easier management using AlpineJS only. At the moment, your example is not properly using the `@entangle` property at all, its just sitting there collecting dust.

Livewire will call for re-initialization of needed parent nodes when there are changes bound to Livewire itself, like you're doing. The `wire:model` attribute is currently calling for a DOM update on your child `div` to ensure the latest changes are in sync between the DOM and also to your AlpineJS component.

This may be more of an Alpine thing, since Alpine doesn't really know if there are meaningful changes to its own element definition when you update your input field.

Please [take a look at this example](https://laravelplayground.com/#/snippets/d1fe35e6-bc5e-44db-a459-1bdd9fb8ab86), which uses [Alpine's `x-model`](https://github.com/alpinejs/alpine#x-model) attribute to properly proxy your property with Livewire.

If the issue still persist, I would love to see another example which is closer to your current implementation. If not possible in a playground, some copy-pastable snippets may do :wink:.

**Comment by mokhosh** [comment]
I don't understand your preoccupation with real-worldness of the playground. I tried to replicate the technical issue, and of course it's not a complete example of what I'm doing. You would have to read a lot of unrelated code if I copy pasted a thousand lines of my proper real world usage.

The example you provided doesn't have anything to do with what I'm trying to achieve. Let's forget about meaningfulness of examples, and just focus on the technical side.

Take a look at this example:
https://laravelplayground.com/#/snippets/320c1fb8-384e-4add-88fa-12c11ed46187

I'm not even using or changing `dummy`. I'm only changing `name` and `name` is not `@entangle`d. So it doesn't make any sense whatsoever for my child alpine component to be re-initialized.

**Comment by jszobody** [comment]
I have this issue, even though I'm not using @entangle. I've narrowed it down to a nested/child component.

See here:

https://laravelplayground.com/#/snippets/5e812c86-b8f8-4f9e-9796-344224766803

If you have a nested alpinejs scope with x-init, and livewire renders the top/parent component, x-init will re-run every time on the child.

**Comment by roni-estein** [comment]
Do all these examples have nested components? Perhaps this problem is mis-titled. Also, you may want to get input from @ryangjchandler on this, it may be a good use case for spruce. I haven't needed nested components yet, but it may be related to your issue.

**Comment by ryangjchandler** [comment]
Thanks for the mention @roni-estein. Generally speaking, it's good to avoid nested Alpine components since it _can_ cause issues and doesn't really have any real value, since parent scope is passed down to the child.

What are you using nested components for?

**Comment by psos** [comment]
select2,  widgets,    modals ... ?

**Comment by ryangjchandler** [comment]
> select2, widgets, modals ... ?

Yeah, perfectly fine use case. But you need to be careful that things don't get reinitialised, hence the problems above. I'm guessing that an extra `wire:ignore` might be needed somewhere, or potentially a `wire:key` so that Livewire can diff & patch correctly.

If you have `wire:ignore` on the root component, as well as the nested component, does it make any difference? Admittedly `wire:ignore` should leave the entire DOM tree under the root / parent component alone, but it's definitely worth a shot.

Would need a solid reproduction of both cases to test and help out further too.

If you need to share state between components (nested or otherwise), you could always look into [Spruce](https://github.com/ryangjchandler/spruce) or one of the [magic helpers](https://github.com/alpine-collective/alpine-magic-helpers).

**Comment by psos** [comment]
In my case, I used nested components with propoperties that are reinitalized.
select2 , editable fields in datatable and more...

**Comment by mokhosh** [comment]
@ryangjchandler Thanks for you answer.

I'm currently using nested components for a modal that has `@entangle('show')` which I think is a legit use-case.
And inside that modal I have custom date pickers, markdown editors, and other stuff that are their own components and can't share their state with the modal.
I think if you're componentizing your app, there are a million cases where you would have nested components, and we have to see what the intuitive expected behaviour is and achieve that.
Here, re-initialization doesn't seem expected.

Also, if we put wire:ignore on the whole modal in my example, the re-initialization problem is of course fixed since Livewire doesn't touch is, but that's not an option for me because it also disables my real time validation messages in the modal and other functionalities that I need, like auto completes, etc.

**Comment by ryangjchandler** [comment]
@mokhosh `wire:ignore` will prevent the entire DOM tree from being replaced, you probably want to use `wire:ignore.self` so that the single element that directive is on doesn't get updated / patched, only the children will be updated so any real time validation will still work.

**Comment by ryangjchandler** [comment]
Also, my previous comment about avoiding nested components was more related to when you need to share data between a parent and child.

**Comment by mokhosh** [comment]
@ryangjchandler tried `wire:ignore.self` and it doesn't work. Only `wire:ignore` does and it breaks everything else.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mokhosh** [comment]
REOPEN

**Comment by AshleyMinshall** [comment]
> I also have it I see. Seems to happen on my end because the component is shown conditionally.
> When I show the component unconditionally x-init is not called multiple times in my case.

I have the same issue, though I haven't done any testing to show that it is because of nesting.
What I have done instead is this:

```blade
<div wire:ignore>
    <div>
        <select multiple x-data="{
            {{-- viewers: {{ collect($viewers) }}, --}}
        }" x-init=" () => {
            {{-- console.log('x-init'); --}}
        {{-- select = new SlimSelect({
            select: $refs.input,
            showSearch: false,
            onChange: (info) => {
                ids = info.map(i => i.value);
                $dispatch('input', ids);
            },
            addToBody: true
        });
        v = JSON.parse(JSON.stringify(viewers));
        console.log(v);
        select.set(v);
        console.log(select.selected()); --}}
        }
        " name="viewers" id="viewers" class="w-full">
            @foreach($viewerOptions as $v)
            <option value="{{ $v->id }}">{{ $v->first_name }} {{ $v->second_name }}</option>
            @endforeach
        </select>
        @push('js')
        <script>
            document.addEventListener('livewire:load', function () {
            // @this.on('load', () => {
                select = new SlimSelect({
                    select: "#viewers",
                    showSearch: false,
                    onChange: (info) => {
                        ids = info.map(i => i.value);
                        @this.set('viewers', ids);
                        // console.log(ids);
                        // $dispatch('input', ids);
                    },
                    addToBody: true
                });
                @this.on('updatedViewers', () => { // annoying
                    select.set(@this.viewers);
                });
            });
        </script>
        @endpush
    </div>
</div>
```
I'm trying to make use of https://github.com/brianvoe/slim-select for a multiselect (It's very nice).
You can also see my commented out alpine code to see what I tried.

While not as clean as alpine/@entangle solution, this works. The only annoying thing is the:
```blade
@this.on('updatedViewers', () => { // annoying
```
because you have to 
```php
$this->emit('updatedViewers');
```
every-time you change the variable (in this case viewers) from the component (Unless there is an event that I can listen to that will work every-time there is a reload).

Also, is there documentation on the 'livewire:load' event? I found it in https://laravel-livewire.com/docs/2.x/inline-scripts but it would be nice to have a list of all the events I can hook into. Like livewire:refresh for this case

Thanks
CoffeeKing

**Comment by thumbtech** [comment]
I have noticed this (or very similar issue) here and there, particular while using the jetstream-y modal dialogs with color pickers, date pickers, etc., where you end up with nested x-data. You can actually reproduce in the livewire/surge demo if you place a console.log message in the x-init script for the Pikaday date picker component in the edit modal; the date picker is init-ed repeatedly as you show/hide the modal. If you try to get fancy with $watch callbacks, etc., in these cases, it can get ugly.

For me, if I call the following component in a vanilla TALL stack and click the "Button Counter" button, I can see that the Inner init is fired off repeatedly. Is that expected? I feel like if I understood why, then it my steer me in the right direction to have inits just run once ... ?

`<livewire:nasty-nesty />`

```
namespace App\Http\Livewire;

use Livewire\Component;

class NastyNesty extends Component
{
    public $counter = 0;

    public function increment()
    {
    	$this->counter++;
    }

    public function render()
    {
        return <<<'blade'
            <div x-data x-init="console.log('Outer init just once please')">
	            <div x-data x-init="console.log('Inner init just once please')">
	                <button wire:click="increment">Button Counter {{ $counter }}</button>
	            </div>
            </div>
        blade;
    }
}
```

**Comment by Mushr0000m** [comment]
Same issue here, having encapsulated component with each one having an `x-init` makes the children init called each time livewire render the HTML. In our case it's causing the third party libraries to create infinite instance. FIY we don't use @entangle it looks more like an issue with encapsulated components using alpine + livewire... I hope we missed something simple to fix this.

**Comment by PH7-Jack** [comment]
Same problem in here
`<div x-data="{name: 'parent'}" x-init="() => console.log('initialized parent')">
        <span x-text="name"></span>
        <div key="foo" x-data="{name:'child 1'}" x-init="() => console.log('initialized 1')">
            <span x-text="name"></span>
            <div key="bar" x-data="{name: 'child 2'}" x-init="() => console.log('initialized 2')">
                <span x-text="name"></span>
            </div>
        </div>
    </div>`
    
    
![image](https://user-images.githubusercontent.com/38913462/111414852-8436ee00-86bf-11eb-908b-a4f09f6d3eff.png)

**Comment by joshhanley** [comment]
I believe recent $wire fix also applies to this issue. Please update Alpine to 2.8.2 to get the fix (there is no Livewire update needed).

Let me know if it doesn't and I will reopen 🙂

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
