### ISSUE TITLE
Select box is broken after installing Livewire.

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#1851]
The preselected value or the 1st option of each and every select box is not working, when trying to store, edit or submit the desired input into the database or the server. It was working all fine before, but since Livewire, it isn't working the way it should. Due to this the validation is also not working for the select box in specific. I need a solution instead of a workaround. Please help me out with this.

**Comment by danharrin** [comment]
Hey, please open a Discussions thread with a code example. Many thanks.

**Comment by mblarsen** [comment]
It is because Livewire only syncs the value on change and you cannot select the first (already selected value). This is both terrible UX and DX. 

I get around it in two ways. 

1. Add a disabled "Select" option with value "" to all selects. 
2. Preselect the first value in mount.

In some places I use Livewire only as a fancy dynamic form but post in the old school way. In this case it is less of an issue.

**Comment by toxifiedmatrix** [comment]
@mblarsen Thanks Mate! Ill surely give it a try. 👍
