### ISSUE TITLE
Empty nullable numeric field raises mysql exception

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1950]
### Description
I have a `integer()->nullable()` field in my database. I `wire:model` an input for the user to put in a number or leave it blank. And I validate this property with `nullable|integer`. But when the user tries to update the field with an empty value, they get this error:
```
General error: 1366 Incorrect integer value: '' for column 'amount'
```
Because livewire passes this as an empty string instead of null.

I'm not sure why having untrimmed empty strings instead of null is the desired behaviour in Livewire.
This issue has been raised before, but we haven't got an explanation why this is.
https://github.com/livewire/livewire/issues/823

**Comment by amirzpr** [comment]
Same issue here.
How empty string values can be converted to `null`?

**Comment by calebporzio** [comment]
Please reference my response from #823

> Not trimming strings and converting to null is the desired behavior of Livewire.
> 
> You can add traits to bypass this and that's what I would recommend if you want to re-introduce this behavior.
> 
> Closing this. Thanks!

There are 2 reasons for doing this:
A) If we kept Laravel's trim strings middleware, it would modify Livewire data at a network request level, which would cause errors because Livewire uses checksum to ensure data preservation. Therefore we CANT use Laravel's TrimStrings/EmptyStirngsToNull things as normal

B) I personally feel like it's more predicatable to NOT mutate empty strings into nulls at a data level. This kind of makes sense as a default for Laravel, but imagine scenarios where you are using `@entangle` with Alpine data and doing some kind of string manipuation with that data (`.toUpperCase` or something). If Livewire heavy-handedly changed all empty strings to null, you would get a `.toUpperCase doesn't exist on null` type thing. Additionally, that behavior is only effecting the root level of data, so nested data WOULDN"T behave this way which is even more confusing for people.

Anyhow, those are the reasons. Please take my earlier advice and use hooks, traits, or manual code to make that happen for yourself.

Thanks.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mokhosh** [comment]
Very nice. This sort of knowledge should be in the docs I think.

**Comment by isometriq** [comment]
You can use something like this, from the default Laravel middlewares
```
public function updated($property, $value) {
    // any fields update
    $this->{$property} = $this->cleanInput($value);
}

public function submit() {
    // ..or before saving specific fields, etc
    Model::update($this->cleanInput($this->formFields));
}

protected function cleanInput($input) {
    foreach ($input as &$value) {
        if (is_array($value)) {
            $value = $this->cleanInput($value);
        }
        else if (is_string($value)) {
            $value = trim($value);
            if ($value === '') {
                $value = null;
            }
        }
    }
    return $input;
}
```

**Comment by phh** [comment]
I think its fine with all the reasoning, however this doesnt change the fact that it you want to you model binding on a `<select>` with the default `<option value="">` then it will send an empty string to the `Model::Update()` and fail if you expect a null or an integer (like when adding an optional category filter)
