### ISSUE TITLE
Error occurs in CPanel site when calling livewire actions

### ISSUE THREAD

**Issue by chamkhangwey** [livewire/livewire#2084]
Hi, not sure if this post should be here. please advice me where should i ask the question if here is not suitable.

I am using Laravel 8 with livewire to create a website.

It works fine until I migrate it to CPanel.

I followed the guide from YouTube to split the whole directory into 2 parts, public_html/shop/v1 contains the public directory with index.php, and public_html/shop_main contains all the codes and files.

It shows this error but I fix it by adding the line 'asset_url' => 'http://myhost.com/shop/v1', in config/livewire.php.

![截圖 2020-11-23 上午3 15 06](https://user-images.githubusercontent.com/43119724/100000747-fe83ef80-2dfc-11eb-87b5-ee80fd124da2.png)
Uncaught ReferenceError

Then I encounter another problem with livewire. The error occurs when i try to change the combo box value which bind to livewire public property.

![截圖 2020-11-23 上午3 24 01](https://user-images.githubusercontent.com/43119724/100000794-10fe2900-2dfd-11eb-8e1b-be540bfae99f.png)
New error appears

I hardly find any references online regarding this error. By the way, livewire-products is the livewire component to show the product.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by joshhanley** [comment]
I don't think this is a Livewire issue as you are trying to use Laravel in a non-standard way.

I'm not familiar with installing Laravel on a cPanel account, so can you explain to me why you split the directory into two parts and link the youtube video you watched?

What it looks like to me is the routing isn't working properly. You will probably find that the Livewire endpoint `livewire/message` is being run at the root path `http://xotalents.com/livewire/message` instead of in your sub directory. So you will probably need to work out how to change your apps base path to include the sub directory.

But, be aware, it's not advised, nor secure to put your code inside a public directory. Only your index.php and assets should be inside public_html, everything else (everything that is in `shop_main`) should be outside the public folder, in your home folder or a sub-folder under your home folder.

**Comment by chamkhangwey** [comment]
Hi joshhanley,
This is my first time working on Laravel and Livewire as well as CPanel, I could be doing something wrong.

The reason I use subdirectory to store my website is because the main domain already has a working website. I am utilising the subdomain to publish another website. This is the video I referred to to guide me publish the website: https://www.youtube.com/watch?v=6GQGYaxlSpU

As what you said, I must publish Laravel website with Livewire in public_html but no subdirectory (subdomain)?

I did added this line in config/livewire.php --> 'asset_url' => 'http://xotalents.com/shop/v1', and it fixes my first error. What else should I configure in order to fix second error?

**Comment by joshhanley** [comment]
That's ok!

Have a look at this https://driesvints.com/blog/laravel-4-on-a-shared-host and this https://laravel-news.com/subfolder-install.
They should give you some more information on the security aspect. 

You will need to ensure in your .env file that your APP_URL contains your full URL with subdirectories. See if changing this helps.

**Comment by chamkhangwey** [comment]
Hi joshhanley,

It still won't work.
I have tried updating the livewire version to latest version by running `composer update livewire/livewire` and republish the livewire (php artisan livewire:publish --assets), but failed.

I tried to change the subdomain to domain.com/shop3/public and deploy the project to shop3 and the public directory to shop/public, it show extra error.

![截圖 2020-11-27 下午11 44 44](https://user-images.githubusercontent.com/43119724/100465648-a4d83980-310a-11eb-957b-53e1b95f3c00.png)

I was expecting a simple deployment to CPanel. I really don't know how should I further debug.
The worst case for me is to abandon livewire and re-code my webpages using javascript instead.

**Comment by joshhanley** [comment]
@chamkhangwey CORS policy is a different error than you were getting before. That's not a Livewire specific problem, that's more to do with how Laravel works and is secure. I would make sure all your app urls have been updated, and do some research on how CORS works.

I will be honest though, I would not expect deploying to cPanel to be a simple process as it's not a standard configuration of Laravel and Livewire. It can certainly be done, but needs extra configuring and potential troubleshooting of edge case issues like you're having. Plus you are trying to run it out of a subfolder, which also complicates it more. Trying to do a setup like that if you are new to both Laravel and Livewire will be tough, but not impossible.

If you want a simple deployment, I would be considering using a server, deployed through something like Laravel Forge, as it is configured correctly and just runs out of the box.

But I wouldn't be throwing it all away just because it's harder to setup. As you will know, with developing your app locally, that Livewire is nice to use. So once you have gone through all the effort to finally work out how to run this on cPanel like you are hoping, then it will be much easier next time, and you get the joy of using Livewire to develop with! Also consider writing up a blog article or something to share how you solved these issues.

One thing you could do to potentially simplify it, is running it on a subdomain. Is there any reason you can't do that? Maybe setup a new subdomain like `shop.domain.com` so everything will be running in the base folder for the subdomain, rather than using a subfolder on the main domain.

Don't give up hope!
Hope this helps!

**Comment by chamkhangwey** [comment]
Hi joshhanley,
I managed to make the livewire works. Thanks for your helps.

I will explain here in case there are people having the same problem who are looking for solution.

My subdomain is shop.mysubdomain.com, and my document root is public_html/shop

The fail case:
I was setting the 'asset_url' => 'http://mysubdomain.com/shop', in config/livewire.php, which it solved my Uncaught ReferenceError but introduced the POST not found error (see the descriptions on the top).

The working case:
I changed the asset_url to 'asset_url' => 'http://shop.mysubdomain.com', and this solve all the errors above, and livewire is working.

Thanks again for the comments.

**Comment by austenc** [comment]
@joshhanley Thank you for helping resolve this. 

@chamkhangwey would you mind closing this issue since you've now solved the issue? Thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@chamkhangwey good work! It's great to see your perseverance pay off 😁

**Comment by onderic** [comment]
Also facing this problem on cpanel 'UnexpectedValueException
Invalid route action: [App\Http\livewire\HomeComponent].
https://car.shwariba.co.ke/
Hide solutions
`App\Http\livewire\HomeComponent` was not found.
Controller class App\Http\livewire\HomeComponent for one of your routes was not found. Are you sure this controller exists and is imported correctly?' but the same project works correctly in local host

**Comment by chamkhangwey** [comment]
@onderic,
Hi, i am not an expert here, I am just a Livewire user just like you. I just want to help. So please don't mad at me if I give you the wrong solution. XD

Do you set your domain or subdomain name correctly in .env file? APP_URL=http://yourdomainorsubdomain.com

**Comment by onderic** [comment]
have tried it but still getting same error
