### ISSUE TITLE
Error when validateOnly model property doesn't exist in rules

### ISSUE THREAD

**Issue by dtc13579** [livewire/livewire#2094]
### Description
It appears the fix applied in [1625](1625) doesn't handle a similar situation with a model property.

i.e. If a model property doesn't have a validation rule, an exception is raised:

Livewire\Exceptions\CannotBindToModelDataWithoutValidationRuleException
Cannot bind property [model.name] without a validation rule present in the [$rules] array on Livewire component: [test].

### Exact steps to reproduce
1. Create a component with a model
2. Don't define a validation rule for a property in the model
3. Call `validateOnly($field)` in the `updated($field)` hook
4. Update the property which doesn't have a validation rule

### Stripped-down, copy-pastable code snippets

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;

class Foo extends Component
{
    public User $model;
    public string $baz = '';

    protected array $rules = [
        'baz' => 'required',
    ];

    public function updated($field): void
    {
        $this->validateOnly($field);
    }
}
```

`<input wire:model="model.name">`

**Context**
- Livewire version: 2.3.2, also confirmed in dev-master
- Laravel version: 8.16.0
- Browser: Chrome

**Comment by joshhanley** [comment]
@dtc13579 you can't use model properties like that, you need to have a rule for model.name as any model properties must have a rule defined for it to be accessed by the front end. That is by design as it's more secure, as you have to be specific as to what should be accessible/editable on a model. See here https://laravel-livewire.com/docs/2.x/properties#binding-models
>Note: For this to work, you have a validation entry in the `$rules` property for any model attributes you want to bind to. Otherwise, an error will be thrown. 

It will be getting that error when updated is called.

If you want to run validateOnly when $baz is updated, then be more specific by creating a method `public function updatedBaz()` instead.

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
