### ISSUE TITLE
Binding Directly To Model Properties, And Displaying The Role Of A User Through The Pivot Table

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2121]
Laravel Livewire has already explained it very well on how to bind directly to model properties. Through that I can display the data of the concerned user in the appropriate input space, while editing a user, with the name of the user, the email and so on.

How can I display the role of the concerned user which has `BelongsToMany` relation and relates to the role of the user, using a role_user pivot table. How can I display the role of the user without using the mount function and with the method mentioned below as I am successful in showing the name and the email of the user, by adapting to the below piece of code.

I was able to pursue the above said action using the old method mentioned below, please help me to achieve the same results with my current approach, which is by binding directly to models.

```
public function edit($id) {
    $user = User::findOrFail($id);

    if ($user) {
        $this - > primaryId = $id;
        $this - > name = $user - > name;
        $this - > email = $user - > email;
        $this - > role = $user - > Roles - > pluck('id');
        $this - > showModal();
    }
}
```
**Current & Latest Approach**
Component Controller
```
public User $user;

protected $rules = ['user.name' => 'required | string | max:255',
    'user.email' => 'required | string | email | max:255 | unique:users,email',
    'user.role' => 'required'
];

public function edit(User $user) {
    $this - > user = $user;
    $this - > showEditModal = true;
}
```

Component Blade
```
<x-input.group for="name" label="Name" :error="$errors->first('user.name')">
    <x-input.text wire:model="user.name" id="name" placeholder="Name" />
</x-input.group>

<x-input.group for="email" label="Email" :error="$errors->first('user.email')">
    <x-input.text wire:model="user.email" id="email" placeholder="Email" />
</x-input.group>

<x-input.group for="role" label="Role" :error="$errors->first('user.role')">
    <x-input.select wire:model="user.role" id="role">
        <option value=""></option>
        @foreach ($roles as $role)
        <option value="{{ $role->id }}">{{ $role->name }}</option>
        @endforeach
    </x-input.select>
</x-input.group>
```
**EDIT**
I am able to get value of the role of the user through the pivot table, using the below source code but I am unable to sync roles in the database, due the new method of validating rules and saving a user. Please tell me If I ain't doing it the livewire way or doing it incorrectly. 
```
public User $user;

protected $rules = [
    'user.name' => 'required | string | max:255',
    'user.email' => 'required | string | email | max:255 | unique:users,email',
    'user.role' => 'required'
];


public function edit(User $user) {
    $this - > user = $user;
    $this - > user - > role = $user - > roles - > pluck('id');
    $this - > showEditModal = true;
}

public function save() {
    $this - > validate();
    $this - > user - > save();
    $this - > user - > roles() - > sync($this - > role);
    $this - > showEditModal = false;
}
```

This is the old approach of syncing the roles and saving it along with the user. How can I do the same but with the latest approach, using the model property binding.
```
$this - > validate(
    [
        'name' => 'required|string|max:255',
        'email' => 'required|string|email|max:255|unique:users',
        'role' => 'required'
    ]
);

$user - > update([
    'name' => $this - > name,
    'email' => $this - > email,
]);

$user - > Roles() - > sync($this - > role);
```

**Comment by joshhanley** [comment]
@toxifiedmatrix how come you don't want to use the mount() method? That is a core method in how Livewire works, so I wouldn't be avoiding it!

I would recommend putting another property `public Role $role;` on your component and binding the select dropdown to that. To populate it's initial value, in your mount method, use `$this->role = $user->role`.

Then in your save method you can attach `$this->role` to use as you have shown in your edit (but this currently won't work as it doesn't look like you have `$this->role` defined).

Hope this help!

**Comment by skeeith** [comment]
I prefer you to move this question to Laracasts so a lot of devs can look into this, as this is not really an issue towards Livewire, but rather how you should implement this. You will get more responses there and they will surely ignore or close this.

**Comment by skeeith** [comment]
As for your problem or concern, there's a lot of ways you can do this. There's no really a proper or correct way of doing this, to be honest. For as long as it works and you're not doing too much tricky stuff, you should be fine. Also, separating the fields has its advantages for finer control over the fields rather than using an Object direct and just accessing the attribute.
look at what @joshhanley said, that pretty much solves your problem.

**Comment by toxifiedmatrix** [comment]
Problem solved! Thanks @joshhanley @skeeith

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@toxifiedmatrix no worries!

@skeeith may I ask, have you had any issues ignored here or closed without a response? As your first comment reads like you aren't happy.

There are a lot of good devs who help out in this Livewire repo and on Livewire discord, and as such don't think you necessarily should go to Laracast forums over this repo.

But I would recommend opening a discussion over an issue for problems like @toxifiedmatrix was having as it is more of an implementation issue rather than a bug.

Caleb also allows you to reopen issues if you think it should be reopened (see above comment from squishy).

If you think something can be handled better, please let us know!

p.s. @toxifiedmatrix sorry for hijacking your thread (I waited until your issue was resolved first 🙂)

**Comment by skeeith** [comment]
@joshhanley oh no, I just thought this is not the place for asking these kinds of questions since this is not an issue or a bug on Livewire but rather how one would implement it, so I thought of suggesting a place where devs usually respond really quick like Laracasts forum, so he would get a lot of help from other devs. Devs in Laracasts are pretty quick to answer there, it's kinda my first go to when I have questions like what the author has here :)

As for the experience here in the `Issues` tab? pretty good I must say :)

**Comment by joshhanley** [comment]
@skeeith ah ok, fair enough! 🙂  Another option for quick Livewire responses, I would recommend the discord, it's a really good community there https://discord.gg/livewire

That's good to hear! 😁

Have a good week!

**Comment by fahad-imran** [comment]
bvvvvvvvvvx
