### ISSUE TITLE
Resurrect WebSockets

### ISSUE THREAD

**Issue by tillkruss** [livewire/livewire#216]
When polling several components on the same page (for example unread messages, notifications and messages of the current chat), the server gets quite busy, even if nothing happens.

Reducing the polling rate might make sense in some cases, but can result in delays in the UI. Using caching results in a cache invalidation nightmare.

This could be solved by either grouping calls with the same interval or resurrecting WebSocket support as an alternative to the default XHR implementation.

**Comment by calebporzio** [comment]
I think grouping polls on the same interval would be 🔥 (and not all that hard to write)

Having a robust enough WebSocket driver to manage concurrent connections and allow backend events to push to components on the front-end would be some real heavy lifting. And then the problem of how to get this all to work for people in production contexts reliably and not cost an insane amount.

Don't get me wrong, I think there is HUGE potential for Livewire and WebSockets, I just haven't seen a clear path yet that I'd be confident heading towards. Thoughts?

**Comment by tillkruss** [comment]
I think group polls would be rad, especially if it’s easy. 

My biggest issue is responsiveness when it comes to polling. 10s intervals feel sluggish. 2s intervals feel good, but create a lot of server load. Caching would fix this, but is relatively hard in my particular case. 

WebSockets seem like the perfect solution, since it’s nearly instant but only causes execution when needed. 

Your worry about WebSockets is the server-side, correct?

**Comment by calebporzio** [comment]
Yes, my worry is entirely server-side. 

In these cases, what's wrong with using the Echo/Pusher integration? Does it feel tacked on or something? Or like you mentioned, you want something that just works locally in development without adding API keys and hitting a live server locally.

**Comment by defenestrator** [comment]
Python has some amazing looking tools for websockets, I am not even a novice with Python, but this may inspire some interesting ideas:
https://www.starlette.io/
I an going to check it out a bit.

**Comment by calebporzio** [comment]
Looks super powerful, if only it existed for PHP...

**Comment by tillkruss** [comment]
Summary of our chat:

- Integrate closely with Pusher
- Serve different JS bundle (if enabled)
- Offer wrapper around PHP SDK in `Livewire::class`
- Offer wrapper around JS SDK in `window.livewire`
- Offer easy development/testing dropin replacement
  - https://github.com/dimiro1/ipe
  - https://github.com/edgurgel/poxa

**Comment by ashleyhood** [comment]
This is what we use as a Pusher replacement:
- https://docs.beyondco.de/laravel-websockets/

**Comment by axit-joost** [comment]
> In these cases, what's wrong with using the Echo/Pusher integration? Does it feel tacked on or something? 

The 'problem'  is that Echo/Pusher is more or less a one-way street: Stuff happens on the backend, it gets observed and it gets pushed through to the frontend. Also, it is too much centered around the concept of Channels (Public, Private and Presence).

WebSockets are two-way, meaning that we should be able to get the frontend to communicate with the backend as well. The problem with Laravel Echo, is that its community supported offering is a totally separate node app. It doesn't know (or need to know) anything about your PHP app. You would still need to communicate with the PHP world via Ajax/XHR, the only difference might be that the result might go over WebSockets as you would want to update all live connected clients.

As @ashleyhood mentioned, Beyond Code's Laravel WebSockets lives in the PHP world (Ratchet) so the benefit is that one can intercept the messages that come in over WebSockets and since we are already in the PHP world (Laravel), it should be possible to do the same thing that happens now over Http.

**Comment by calebporzio** [comment]
No plans on this right now.
