### ISSUE TITLE
What is the minimum version of Laravel for livewire v2 ?

### ISSUE THREAD

**Issue by zvlad** [livewire/livewire#2213]
What is the minimum version of Laravel for livewire v2 ?

This is not stated in the documentation.
I use Laravel 6.
Installed livewire v2 and the template does not work <livewire:counter />
Why?

**Comment by joshhanley** [comment]
@zvlad the minimum is Laravel 7, so that will be why your component won't work.

I'm surprised composer didn't throw any errors when you installed Livewire as it should have told you it wasn't compatible.
See this issue #2201 asked yesterday as an example of what composer should have done.
Please try to search issues for answers first. 🙂

You can find the information on supported versions of Laravel in any package by looking at composer.json inside a package and seeing what versions are listed next to illuminate/support. For example this is Livewire's:
`"illuminate/support": "^7.0|^8.0",`

Hope this helps!

**Comment by zvlad** [comment]
That's why I wrote to you about the version. I thought it would give some error during installation. But no. Installed without errors. And it works if you connect not so `<livewire:counter />`, but so `@livewire('counter')`

**Comment by joshhanley** [comment]
@zvlad no worries, it's possible that composer only installed version 1. To check that, can you run `composer show -D` and paste the output here?

Ah ok, so that is a Laravel issue, not a Livewire one. This syntax `<livewire:counter />` is the new blade component syntax that was introduced in Laravel 7, hence why it won't work on your system, but `@livewire` will. Check them out here if you are interested https://laravel.com/docs/8.x/blade#components

**Comment by austenc** [comment]
This probably should be in the docs, feel free to PR it here:
https://github.com/livewire/docs

As Josh mentioned, Livewire requires Laravel 7+

Closing since this isn't a bug. Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
