### ISSUE TITLE
Infinite request loop

### ISSUE THREAD

**Issue by joostvanhoof** [livewire/livewire#2236]
This is an issue I've been trying to solve for weeks now. In short: an infinite request loop happens when selecting multiple product filters (think ecommerce sidebar to filter products).

It's a pretty interesting issue, and even with the help of a (paid) expert I've not been able to fix it. There are many details to it that I've described in [this SO post](https://stackoverflow.com/questions/64731832/laravel-livewire-wireclick-creates-infinite-loop).

I know this is unconventional but I'm happy to jump on a call and walk someone through this to show the code and what's happening in detail.

**Comment by joostvanhoof** [comment]
Thanks, really appreciate it. The files are quite large to put here and explain (as you can see from the SO post) so I'll add you to the repo. Please feel free to connect with me on joostvanhoof@gmail.com if you have any questions.

Once you've setup the project locally: if you select 2 or more colors the infinite loop starts.

I also get the infinite loop on production without the color filters when selecting multiple different filters (seems random, can't pinpoint when it exactly happens) but I don't get that on my local environment. I expect this is related. As indicated I'm happy to jump on a call and walk you through it.

**Comment by joshhanley** [comment]
@joostvanhoof sorry I missed your reply! Did you end up solving this? If not, can I suggest you join the Livewire discord and we can connect through that and see if we can work through it? https://discord.gg/livewire

**Comment by joostvanhoof** [comment]
No worries at all. Haven't solved this yet. I did add you to the repo, so feel free to check that out. You can use the vahn branch. 

I'll connect over Discord directly after Christmas! 🎄

**Comment by joshhanley** [comment]
@joostvanhoof I just found your invite email, but it said it has expired 😑  can you send again?

**Comment by joostvanhoof** [comment]
No worries, just re-invited you. Please use the `vahn` branch. If you uncomment the color filters, you'll see the infinite loop if you select 2 or more. You're 10 hours ahead of me so not sure if we can connect today, else I'll try tomorrow. Or send an email. Thanks again!

**Comment by joshhanley** [comment]
Ok I finally got in 🙂 The problem is a morphdom issue. 

The code that is triggering the errors and the loop is the `wire:loading` on your heading row and products row. 

The reason is, when you select two or more colours, there are no results shown. What happens then is you're swapping from showing heading/products/total to showing an empty state.

But morphdom doesn't know by default that it should delete the old divs and add the new one. Instead it is trying to "morph" the old first div into the new one. That means that the wire:loading listeners are still registered when they shouldn't be. Hence why the error and the loop.

It's a simple fix though. You need to add wire keys to the divs defining what they are, so morphdom knows that they have actually changed completely, and to delete the old ones and add new ones.

Have a look at this screenshot below of the diff for what I did to get it working. I added a wire key for all the top level divs inside this file.

It's recommended whenever using conditionals like that to add wire:keys to any elements that are first level inside the conditional, so morphdom knows there has been a change. It's the same problem VueJS has, where keys are required inside loops.

Hope this helps!

![image](https://user-images.githubusercontent.com/882837/103244854-64423900-49b2-11eb-8871-beb3368bf3ba.png)

**Comment by joostvanhoof** [comment]
You've just fixed a bug that I was struggling with for weeks, thanks so much! If want you can post the answer [on SO](https://stackoverflow.com/questions/64731832/laravel-livewire-wireclick-creates-infinite-loop) and I can mark it as the final answer. Not sure if you'd still get the +100 bounty as I think it expired but would still be nice for you and good for the community. Thanks again!

**Comment by joostvanhoof** [comment]
Forgot to close...

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@joostvanhoof No worries! Didn't have a SO account so had to create one 😆 Have posted the answer over there too!
