### ISSUE TITLE
Livewire\Exceptions\MethodNotFoundException Unable to call component method. Public method [gotoPage] not found on component: [frontend.pages.home]

### ISSUE THREAD

**Issue by prantaDutta** [livewire/livewire#2330]
### Description
I am new to livewire and this might be a noob mistake.
I was testing an application where I have a home component and inside I have a Navbar component. Now When I try to access a method inside the Navbar component which was written in Navbar.php (not blade) I couldn't access it. The error was saying the method was not found on the home. Now I am using a layout component and the navbar component is inside the layout component and the layout component is inside the home component. 

### Exact steps to reproduce
The app structure:
   home
   --layout
   ----navbar
I described the steps above.
### Stripped-down, copy-pastable code snippets
Here's my code.
in my navbar.blade.php
```
   <button wire:click='gotoPage("login")' >Login</button>
```
in my navbar.php
```
    public function gotoPage()
    {
        return view('livewire.frontend.pages.login');
    }
```
Now my question is why is it trying to find the gotoPage method inside the home component when the method should have been called from the Navbar component.  

**Context**
- Livewire version: 2.3
- Laravel version: 8.12
- Alpine version: not using
- Browser: Chrome, Firefox

**Comment by joshhanley** [comment]
@prantaDutta can you share some more code or a working example on https://laravelplayground.com so we can try and troubleshoot it?

**Comment by prantaDutta** [comment]
@joshhanley sorry, I am not familiar with laravel playground. This is my GitHub repository of the project: https://github.com/prantaDutta/livewire-works

**Comment by joshhanley** [comment]
@prantaDutta not sure if you worked it out, but the reason `gotoPage` doesn't work in your nav bar is because it is outside of your Livewire component, so Livewire can't control it, and doesn't know the button has been clicked.

I wrote an article on how to fix that, it uses the new blade component layout style though, I'll link it here and hopefully it might help you. Have a look at the section on making the header interactive. Same issue applies to navbar.
https://joshhanley.com.au/articles/how-to-structure-your-layout-file-for-livewire

Another option is to change the button in the navbar to it's own Livewire component and emit an event when it is clicked, and listen for it in your main component. Have a look at this docs page https://laravel-livewire.com/docs/2.x/events

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by lifegiro** [comment]
You might have forgotton to add "use WithPagination;" in you component class
