### ISSUE TITLE
Dynamic Listener Undefined Index

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#2381]
### Description

As far as I can tell from [these tests](https://github.com/livewire/livewire/blob/1604e434d6653bcf75e07751c500ec44d066340d/tests/Unit/ComponentEventsTest.php), this should work?

```php
protected $listeners = [];

public function mount()
{
    $this->listeners = [
        'my-event' => 'refreshComponent',
    ];
}
```

However, I get the error:

```
Undefined Index: my-event
```

I am testing this in the base component, but my aim is to be able to get it working in a trait using the trait mount method.

**Context**
- Livewire version: 2.2.6
- Laravel version: 8.23.1
- Browser:  Safari

**Comment by boynet** [comment]
see the `getListeners()` method:
https://laravel-livewire.com/docs/2.x/events#event-listeners

**Comment by joshhanley** [comment]
@booni3 I replied on the discord on how to potentially fix that in the trait, copied below in case others are trying something similar.

Hope this helps!

---

\@booni3
>Is it possible to set listeners within a trait? I have tried this but cannot get it working.
```php
public function mountsRedirectsPickSheetScan()
{
    $this->listeners = array_merge($this->listeners, [
        'trait-listener' => 'traitMethod'
    ]);
}
```
> The mount method fires, but adding the extra listener does not.
I get the error "Undefined Index: trait-listener"
Maybe there is a better way to do this to keep all logic within the trait?

@joshhanley 
>Try changing the method name to initializeRedirectsPickSheetScan as that should run every time the component is mounted and hydrated, where as mount will only run on the first initial mount of the component but not after subsequent requests

**Comment by booni3** [comment]
@joshhanley thanks for this. Initialize works...

Your comment seemed to suggest about re-renders but I get the error even if the trait is loaded on first load.

So in summary:

## Doesnt Work
```php
public function mountMyTrait()
{
    $this->listeners = array_merge($this->listeners, [
        'trait-listener' => 'traitMethod'
    ]);
}

public function traitMethod()
{
    dd('OK!');
}
```

```bash
Undefined index: pick-sheet-decoded
```

## Works
```php
public function initializeMyTrait()
{
    $this->listeners = array_merge($this->listeners, [
        'trait-listener' => 'traitMethod'
    ]);
}

public function traitMethod()
{
    dd('OK!');
}
```

I am not sure if this a bug or just undocumented (or I missed it!). Will leave the issue open for now.

**Comment by joshhanley** [comment]
@booni3 awesome to hear it worked!

The reason it errors is because you are dynamically adding in the event listener, as such you need to ensure that it is added each time the component loads, hence needing to use the initialize function.

The mount method only runs when the component is created initially, but not when requests are sent from the front end.

So what is happening is when the request is sent, it's trying to find the event listener 'trait-listener' but it no longer exists, causing the error.

You have to remember Livewire keeps all of its state on the front end and sends through any requirements along with the request. If you have a look you can actually see the listener registered on the front end

![image](https://user-images.githubusercontent.com/882837/105415922-849da480-5c8d-11eb-8174-d4de014aa492.png)

That is why when the request gets back to the backend, it's aware of the listener 'trait-listener' but then can't find it as it's not loaded.

I don't think that's a bug, so I'm going to close the issue. If you think otherwise, please reopen it 🙂

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by caolier** [comment]
https://laracasts.com/discuss/channels/livewire/use-listeners-from-a-trait

  public function getListeners()
    {
        return $this->listeners + [
            'foo' => 'bar',
        ];
    }
