### ISSUE TITLE
Emits from child-components inside named slots don't get delivered.

### ISSUE THREAD

**Issue by budhajeewa** [livewire/livewire#2421]
### Description

If you emit from a child Livewire component, and if your child component is included in the parent component inside a named slot, your emit does not get recognized by the parent component.

### Exact steps to reproduce

1. Have a Livewire component (Parent.).
2. Have a named slot (Eg: `<x-slot name="slot">...</x-slot>`.).
3. Inside that named slot, include a Livewire component (Child.).
4. Emit an event from the child component.
5. Observe that you don't hear the event within the parent component.
6. Take the child component out from `<x-slot name="slot">`, and include the child component outside the named component.
7. Observe that you can now hear the event within the parent component.

### Stripped-down, copy-pastable code snippets

`/app/Http/Livewire/Parent.php`:

```php
namespace App\Http\Livewire;

use Livewire\Component;

class Parent extends Component
{
    protected $listeners = [
        'foo',
    ];
    
    public function foo ()
    {
    	dd('I hear!');
    }
    
    public function render()
    {
        return view('livewire.parent');
    }
}
```

`/resources/views/livewire/parent.blade.php`:

```php
<div>
    <x-slot name="slot">
    	<livewire:child/>
    </x-slot>
</div>
```

`/app/Http/Livewire/Child.php`:

```php
namespace App\Http\Livewire;

use Livewire\Component;

class Child extends Component
{
    public $bar = null;
    
    public function updatedBar()
    {
        $this->emitUp('foo');
    }
    
    public function render()
    {
        return view('livewire.child');
    }
}

```

`/resources/views/livewire/child.blade.php`:

```php
<div>
    <input wire:model="bar"/>
</div>
```

**Context**
- Livewire version: v2.3.6
- Laravel version: v8.22.0
- Alpine version: 2.8.0
- Browser: Firefox, Chromium

**Comment by joshhanley** [comment]
@budhajeewa the reason is probably because, with the child being in a named slot, will be moved out of the parent component by the blade compiler, to wherever your named slot is in your layout.

Once that happens, it's no longer a child, hence `emitUp` will no longer work. Change that to `emit` and it then should work.

Please test it out and let us know how it goes.

Hope this helps!

**Comment by budhajeewa** [comment]
@joshhanley Nope, `emit` does not work either. I should have mentioned that.

Slot "slot" being an special slot, the content gets displayed in the "slot" slot anyway, whether you put it in the slot explicitly or not. But when you do that implicitly (i.e. remove the markup for `slot`.), the child component works as expected.

**Comment by joshhanley** [comment]
@budhajeewa can you explain what you are trying to achieve? Why are you trying to put it in a slot?

The default "slot" like you are talking about still needs somewhere to be output. Where do you define `{{ $slot }}`?

Can you also share your layout?

**Comment by budhajeewa** [comment]
@joshhanley In this particular time, I am just trying to tidy up my code, as it looks nice when I put everything into their intended slots explicitly. However, one might want to put their child components inside a custom slot, as nowhere it mentions in the official docs that you cannot use them in custom components.

I'm on mobile right now, so I am afraid I cannot send you any code. But I'm using the default AppLayout that comes with Laravel Jetstream (Or is it included in Livewire? I don't exactly remember.).

**Comment by joshhanley** [comment]
@budhajeewa I think I understand what you are trying to do, but if that's the case it's not quite setup the way you are hoping. 

Imagine you have your default `app.blade.php` that has `{{ $slot }}` somewhere in it. If you were in a standard blade component, you'd wrap your html in it like
```html
<x-layouts.app>
    Content here
</x-layouts.app>
```
which would put "Content here" into the default slot "slot".

But what you are hoping to do is this:
```html
<x-layouts.app>
    <x-slot name="slot">
        Content here
    </x-slot>
</x-layouts.app>
```

Which will work fine for standard blade components.

The reason why it's not working for Livewire components, is because Livewire auto-populates "$slot", in your layout file, for you with everything that is inside the Livewire component blade view. So by putting another `<x-slot name="slot"></x-slot>` inside the Livewire component's blade view, you've double it up, and when it renders it doesn't know how to handle that.

Also Livewire components don't have the concept of slots, hence why the below code also won't work
```html
<livewire:parent>
    <livewire:child />
</livewire:parent>
```

Hope that all helps give you a better understanding of why it's not working.

I'd recommend creating a named slot other than "slot" if you want to put the child component into a slot on the layout, as "$slot" is already populated with the parent components content.

Hope this helps!

**Comment by budhajeewa** [comment]
@joshhanley That's very informative. I think I grasp it now. Thank you so much for spending your time explaining it in so much detail 🙂🙂🙂!

**Comment by joshhanley** [comment]
@budhajeewa no worries, I'm glad it helped 🙂  One thing to note, if you do decide to use a different named slot to put the child into, the blade compiler will move the child component out from underneath the parent component, into where the named slot is, and that's when you will need to use `$emit` rather than `$emitUp`.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by budhajeewa** [comment]
@joshhanley Sure Josh, I'll do that if I decide to use a custom named slot.
