### ISSUE TITLE
Artisan route:list not working after last update at LivewireManager.php

### ISSUE THREAD

**Issue by nicolaferrara82** [livewire/livewire#2426]
It throws an exception "It's too early in the request to call Livewire::isLivewireRequest()."

Is missing check for console commands.

A solution could be the following at LivewireManager.php line 265:
```php
if (! $route && (app()->runningUnitTests() || app()->runningInConsole())) {
     return false;
}
```

**Comment by joshhanley** [comment]
@nicolaferrara82 I've just tested this on a test Livewire app running 2.3.8 and `php artisan route:list` runs fine with both full page components and views with Livewire components in the routes.

There must be something in your app causing the issue.
Can you investigate and provide code so we can replicate the issue?

Hope this helps!

**Comment by nicolaferrara82** [comment]
Yes it's a fresh clone of surge-master app from private Caleb's repository, no changes made.

This is the exception:
```php
  It's too early in the request to call Livewire::isLivewireRequest().

  at C:\laragon\www\surge-master\vendor\livewire\livewire\src\LivewireManager.php:271
    267▕         }
    268▕
    269▕         throw_unless(
    270▕             $route,
  ➜ 271▕             new Exception('It\'s too early in the request to call Livewire::isLivewireRequest().')
    272▕         );
    273▕
    274▕         return $route->named('livewire.message');
    275▕

  1   C:\laragon\www\surge-master\vendor\livewire\livewire\src\LivewireManager.php:280
      Livewire\LivewireManager::isLivewireRequest()

  2   C:\laragon\www\surge-master\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
      Livewire\LivewireManager::originalUrl()
```

If you have access, you can try cloning it to investigate.
I hope I was helpful

**Comment by joshhanley** [comment]
@nicolaferrara82 I've pull the surge repo and ran `php artisan route:list` without any issues.

Looking at your error it's possibly something to do with your setup on Windows (I'm on a mac running Valet).

I'm going to close this as I don't think it's a bug with Livewire. I'd suggest posting on the [Livewire forum](https://forum.laravel-livewire.com/) to see if anyone else has experienced that issue on Windows using Laragon, or potentially even opening an issue on the Surge repo directly (but I don't think many people look there).

If you find you're running into this issue with other Livewire projects and it turns out it's not related to your setup, please reopen this, so it can be investigated.

![image](https://user-images.githubusercontent.com/882837/106369887-3c773400-63a9-11eb-8e8b-691139064794.png)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by nicolaferrara82** [comment]
Hi @joshhanley,

I don't think it depends on my environment because when I run artisan command from console no server is started, 
but the official version of the php executable for windows is used (php-7.4.11-Win32-vc15-x64) set in the environment path, rather it could be something due to the upgrade from laravel version 7 to 8 of the surge app.
As you can see on a fresh install of Laravel 8 and Livewire 2.3.8 I have no issue.
Thanks
```php
Nicola@DESKTOP /c/laragon/www/frontend (master)
$ php artisan route:list
+--------+----------+----------------------------------+-----------------------+------------------------------------------------------+---------------+
| Domain | Method   | URI                              | Name                  | Action                                               | Middleware    |
+--------+----------+----------------------------------+-----------------------+------------------------------------------------------+---------------+
|        | GET|HEAD | /                                |                       | Closure                                              | web           |
|        | GET|HEAD | api/user                         |                       | Closure                                              | api           |
|        |          |                                  |                       |                                                      | auth:api      |
|        | GET|HEAD | livewire/livewire.js             |                       | Livewire\Controllers\LivewireJavaScriptAssets@source |               |
|        | GET|HEAD | livewire/livewire.js.map         |                       | Livewire\Controllers\LivewireJavaScriptAssets@maps   |               |
|        | POST     | livewire/message/{name}          |                       | Livewire\Controllers\HttpConnectionHandler           | web           |
|        | GET|HEAD | livewire/preview-file/{filename} | livewire.preview-file | Livewire\Controllers\FilePreviewHandler@handle       | web           |
|        | POST     | livewire/upload-file             | livewire.upload-file  | Livewire\Controllers\FileUploadHandler@handle        | web           |
|        |          |                                  |                       |                                                      | throttle:60,1 |
+--------+----------+----------------------------------+-----------------------+------------------------------------------------------+---------------+

Nicola@DESKTOP-Q3RMB8N MINGW64 /c/laragon/www/frontend (master)
$ composer show livewire/livewire
name     : livewire/livewire
descrip. : A front-end framework for Laravel.
keywords : 
versions : * v2.3.8
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/livewire/livewire.git c661e295428b2baaff04320d0a9424db5ca72be5
dist     : [zip] https://api.github.com/repos/livewire/livewire/zipball/c661e295428b2baaff04320d0a9424db5ca72be5 c661e295428b2baaff04320d0a9424db5ca72be5
path     : C:\laragon\www\frontend\vendor\livewire\livewire
names    : livewire/livewire

support
issues : https://github.com/livewire/livewire/issues
source : https://github.com/livewire/livewire/tree/v2.3.8

autoload
files
psr-4
Livewire\ => src/

requires
illuminate/database ^7.0|^8.0
illuminate/support ^7.0|^8.0
illuminate/validation ^7.0|^8.0
php ^7.2.5|^8.0
symfony/http-kernel ^5.0

requires (dev)
calebporzio/sushi ^2.1
laravel/framework ^7.0|^8.0
mockery/mockery ^1.3.1
orchestra/testbench ^5.0|^6.0
orchestra/testbench-dusk ^5.2|^6.0
phpunit/phpunit ^8.4|^9.0
psy/psysh @stable
```

**Comment by joshhanley** [comment]
@nicolaferrara82 sorry, turns out I was wrong! Thank you for testing.

I've worked out what's happening with Surge, when I pulled it, I noticed it was using `dev-master`, where as I had changed that to the latest `2.3.8`.

But when I change to `dev-master`, that's when that bug you noticed is happening. So yeah, there is currently an issue with `dev-master` that will be fixed before it is tagged.

Thanks you again for following up and testing just a standard install and confirming that works, that was a great help!

In future, when filling out bug reports, can you please make sure you include the versions of Livewire/Laravel/Alpine that you are using as per the template. That would have helped to understand that you were running on `dev-master`. To find out exact versions, you can run `composer show -D` in your console.

Hope this helps!

**Comment by nicolaferrara82** [comment]
@joshhanley You are absolutely right, I should have specified the correct version and I apologize for this inconvenience,  but I was convinced that by cloning the repo you would have used my same version and since you did not have the problem I hadn't considered that you had downgraded.

You immediately blamed my operating system :D obviously I am joking, but the important thing is that we have come to the conclusion that the issue really exists.

Glad to have been of help in some way.

Best Regards

**Comment by joshhanley** [comment]
@nicolaferrara82 yep, that was my bad, I'd assumed that maybe Caleb had left that there unintentionally, because it was trying to use a local version of Livewire, so I removed the local reference and fixed the version 😆  yep, always best to specify anyway. 

I hope you know it's always Windows fault! 😉  Heh, yeah sorry about that!

**Comment by austenc** [comment]
@joshhanley could you confirm if this is still a problem or not when you get a chance? Thank you!

**Comment by joshhanley** [comment]
@austenc yep this has been fixed.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
