### ISSUE TITLE
Add click-away detection with "wire:clickaway" directive

### ISSUE THREAD

**Issue by MichaelIshri** [livewire/livewire#244]
**Is your feature request related to a problem? Please describe.**
I was needing to detect a click-away when my livewire dropdown list was clicked outside of itself, so that I could hide it. 

For example, when I clicked a button, a Livewire dropdown list would appear. Previously, I would need to click the same button to trigger the `wire:click` function to toggle the hiding/showing of the dropdown. However, I wanted it to hide when I clicked anywhere outside of the dropdown list, similar to a modal.

**Describe the solution you'd like**
I've finally come to a working solution but not sure were to put it in the JS. The mechanics of it are:
- On the element you wish to toggle the visibility, you add a new html attribute `wire:clickaway` and it's value is the name of the Livewire event you wish to emit (wire:clickaway="hideProfileDropdown").
- Then on the PHP class you simply react to the event as normal.

Here's the code, only JS code is required to implement this:

```
<script>
    document.addEventListener('click', function(event) {
        let clickaways = document.querySelectorAll('[wire\\:clickaway]');
        for(let i = 0; i < clickaways.length; i++) {
            var hasClickedInside = clickaways[i].contains(event.target);
            if (!hasClickedInside) {
                event = clickaways[i].getAttribute('wire:clickaway');
                window.livewire.emit(event);
            }
        }
    });
</script>
```
**Describe alternatives you've considered**
- I implemented a solution which added a transparent layer between the dropdown and the page but it meant if anything else was clicked on the page, it wouldn't react.
- I also implemented a solution which would add the element id to a global list of nodes when clicked but it meant that I needed to add JS into each of my components to perform that "add" operation.

**Additional context**
As I mentioned, not sure the best place to add the code so have contributed it here instead of a PR. Hope that makes sense. :-)

**Comment by oliverbj** [comment]
This could be really helpful to have! Especially for dropdowns like you mention.

**Comment by depsimon** [comment]
Would be great if we could trigger an action and not an event, like the `click` event does.

**Comment by calebporzio** [comment]
First, I would say this is a smell because `click-away` is most often wanted for dropdowns and modals, which I think a tool like Project X (https://github.com/calebporzio/project-x) is better for.

Secondly, I'll say, I'm open to adding it to the framework with the same API as Project X (`wire:click.away`), and we can even use Project-Xs implementation (I think).

Although I think this is a good addition, this isn't a high priority for me, so someone would need to submit a well-formed PR with tests for me to merge this in the near future if that makes sense.

**Comment by indigoram89** [comment]
Can someone do this please?

**Comment by weogrim** [comment]
If some one ran to this issue, I have quick fix. It not provide solution to re-render the component and use Livewire powers, but it works fine for hiding/removing an item like dropdown.

In blade layout, right before `</body>` declare section for additional scripts:
```
@yield('additionalScripts')
```

In Livewire component view, outside root div add:

```html
@section('scripts')
    <script>
        const target = document.querySelector('#component-root-div')

        document.addEventListener('click', (event) => {
            const withinBoundaries = event.composedPath().includes(target)

            if (!withinBoundaries) {
                //Place click-away code here. 
                var element = document.querySelector("#element-to-remove");
                element.parentNode.removeChild(element);
            }
        })
    </script>
@append
```

Using `@append` instead of `@endsection` allows to append code to the  `additionalScripts` section, and use this section in multiple components.

If I understand correctly `composedPath` is smart enough to detect if an element is in another element, even when using `position: absolute`.

More about `composedPath`: https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath
Stack answer with snippet: https://stackoverflow.com/a/64665817/2686214

**Comment by marchershey** [comment]
I think this should be bumped up in priority.

As of now, I currently have to use `x-on:click.away="$wire.closeModal()"` so having a `wire:click.away` would be amazing. 

If you're wondering why I need to call a method when closing a modal, because there are certain params I need to validate before the modal closes and it also ensures the user doesn't loose any saved data by accident.

**Comment by Lirux** [comment]
Because it seems that a lot of people use the snippet from @marchershey, what I noticed is that each click in the window generated a Livewire request. No matter if the dropdown/modal was open or not.

So, as workaround I just check if the dropdown is currently open, like so:
`x-on:click.away="if($wire.get('showDropdown')==true) { $wire.hideDropdown() }"`

Also, the `x-on:click.away="$wire.hideDropdown()"` caused a strange issue.
When there was a validation error in the controller (not in the Livewire component) the $errors attribute was empty.

After my workaround, it worked again as expected.

**Comment by gbrits** [comment]
> Because it seems that a lot of people use the snippet from @marchershey, what I noticed is that each click in the window generated a Livewire request. No matter if the dropdown/modal was open or not.
> 
> So, as workaround I just check if the dropdown is currently open, like so: `x-on:click.away="if($wire.get('showDropdown')==true) { $wire.hideDropdown() }"`
> 
> Also, the `x-on:click.away="$wire.hideDropdown()"` caused a strange issue. When there was a validation error in the controller (not in the Livewire component) the $errors attribute was empty.
> 
> After my workaround, it worked again as expected.

Alterntively, if you have initialised / entangled the variable 
(ie, parent container: `x-data="{ hide_dropdown: @entangle('hide_dropdown') }"`)
 things are a bit shorthand:
```javascript
@click.away="if(hide_dropdown==true) { hide_dropdown = false }"
```
