### ISSUE TITLE
assertSet on a non-existing property should fail

### ISSUE THREAD

**Issue by anhofmann** [livewire/livewire#2817]
### Description
Suppose you do this test:

```php
Livewire::test(Foo::class)
                ->assertSet('bar', true);
```

And your component Foo hasn't a 'bar' property, the assertSet() will return true. This makes it easy to have a typo and not realising that a test is green when it really should be red.

### Stripped-down, copy-pastable code snippets

```php
test.php:
/** @test */
    public function it_should_fail()
    {
        Livewire::test(Foo::class)->assertSet('bar', true);
    }
```

```php
component.php
class Foo extends Component
{
    public $baz = false;
   //there is no public $bar
}
```

**Context**
- Livewire version: 2.4.4
- Laravel version: 8.40.0

**Comment by anhofmann** [comment]
Never mind, my real test looked like this: 
```php
Livewire::test(Foo::class)
                ->assertSet('bar', null);
```
So this is expected behavior.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by titantwentyone** [comment]
REOPEN

@anhofmann I've just come across the same issue but I'm unsure why this is expected behaviour. The assertion seems to imply that a property of `bar` is set and that it is `true`. Since this passes, as you suggested, it woudl very easy for a typo to give a false positive (as happened with me). I'm wondering if further assertions are needed - i.e `assertpropertyExists` or indeed whether the presence of a property is something we need to test at all?
