### ISSUE TITLE
Livewire encountered corrupt data when trying to hydrate [] component -> only ios

### ISSUE THREAD

**Issue by asterism612** [livewire/livewire#2849]
desktop(window, macos chrome) well.
android well.

fire error only ios(iphone's all browser, ipad's all browser, mac safari)...

**Comment by drj378** [comment]
I am having the same issue but only in production. Everything was working fine yesterday morning. I pushed no code updates yesterday. I did not redeploy my production Vapor instance. One of my managers was successfully using this specific form all morning and then later that day it stopped working and started returning this error message. I cannot produce the error outside of production. Running the exact same code locally and in staging produces no error. My Livewire instance looks like:

```
    public function mount()
    {
        $this->setOrganization();

        $this->setOptionCategories();

        $this->setRequirements();

        $this->setOptions();

        $this->setTimeSlots();

        $this->key = Str::random(20);
    }

    public function render()
    {
        $categories = $this->findCategoriesSelect();

        $this->option_categories = Category::where([
            ['organization_id', $this->organization_id],
            ['use_case_id', $this->useCaseId],
            ['type', 'option'],
            ['status', true],
            ['deleted', false]
        ])->get();

        return view('livewire.cafe.action.create-item', compact('categories'));
    }
```

The `option_categories` variable was originally in a `hydrate()` function but I removed it from there because the error message said it found corrupt data trying to hydrate. No help.

I've found several other people with the same problem [here](https://stackoverflow.com/questions/63848826/livewire-encountered-corrupt-data-when-trying-to-hydrate-the-component), [here](https://laracasts.com/discuss/channels/livewire/livewire-encountered-corrupt-data-when-trying-to-hydrate-the-invitationsend-component-ensure-that-the-name-id-data-of-the-livewire-component-wasnt-tampered-with-between-requests?page=1#reply=710714), and [here](https://laracasts.com/discuss/channels/livewire/livewire-encountered-corrupt-data-when-trying-to-hydrate-the), but none of the proposed solutions have helped me. Some of them are simply unanswered.

The strangest thing about this error is that it appeared without me changing anything. Does anyone have any ideas what it could be?

Also - I tried adding unique keys to different elements in the view but that didn't help either.

Thanks

**Comment by calebporzio** [comment]
That's tough. Can you strip down the example until submitting works in production, then report the stripped down version that hopefully others or you can test and find the exact problem? Otherwise it's almost impossible to help. Thank you!

**Comment by drj378** [comment]
@calebporzio I was able to solve the problem by changing all Collection instances to arrays by following advice from [this](https://github.com/livewire/livewire/issues/354#issuecomment-841429705) thread (scroll all the way down). All Collections had to be removed even if they were not changed after they were initially declared in `mount()`. Following advice from the other issue, it looks like there is a miscommunication that takes place when data is no longer neatly/plainly stored in a table. Unfortunately, I stumbled upon this by accident so I don't exactly know how to recreate it. Would it be helpful for you if I tried to recreate this issue with a simple app and share what I find? Hopefully I could find some time in the next week or so.

Also, Livewire is awesome and has made my life so much better. Thanks for everything

**Comment by tjimenez** [comment]
Seems to be related to Collections and updating any property with that type will trigger the same exception.

**Comment by hhfa1990** [comment]
Same error:

**index.blade.php**

```
@foreach ($states as $state)
    <livewire:admin.workflow.state.edit :state="$state" wire:key="$state->id"/>
@endforeach
```

**Edit.php**
```
class Edit extends Component
{
    public $state;
    public $name = '';
    public $showModal = false;

    public function mount(State $state)
    {
        $this->name = $this->state->name;
    }


    public function render()
    {
        return view('livewire.admin.workflow.state.edit');
    }

    public function toggleModal()
    {
        $this->showModal = !$this->showModal;
    }
}
```
**edit.blade.php**
```
<div>
    <a href="#!" wire:click="toggleModal" class="text-indigo-600 hover:text-indigo-900">
        edit
    </a>

    <x-jet-dialog-modal wire:model="showModal">
        <x-slot name="title">Edit status</x-slot>

        <x-slot name="content">
            {{ $state }}
        </x-slot>

        <x-slot name="footer">
            
        </x-slot>
    </x-jet-dialog-modal>
</div>

```
