### ISSUE TITLE
`wire:loading.attr` overrides `wire:loading.class.remove` overrides `wire:loading.class`

### ISSUE THREAD

**Issue by assertchris** [livewire/livewire#334]
It doesn't appear to be possible to use attribute and class[.remove] together. 

**Expected behavior**
I would like to be able to use Tailwind (without also writing custom CSS to support visual changes when only disabled attribute is changed).

**Comment by stefanbauer** [comment]
I noticed the same. Well, quite the same. What I found out is, that the order matters.

**What doesn't work:**

```html
<button wire:click.prevent="submit" wire:loading.attr="disabled" wire:loading.class="opacity-50" class="w-full">
    Sign up
</button>
```

**What works:**

```html
<button wire:click.prevent="submit" wire:loading.class="opacity-50" wire:loading.attr="disabled"  class="w-full">
    Sign up
</button>
```

As soon as you define the loading class before the loading attributes, the class gets applied, otherwise not. I think this is a bug. Can anyone confirm it?

/cc @calebporzio

**Comment by Te7a-Houdini** [comment]
@assertchris  @stefanbauer is this issue still happening or is it solved ?

**Comment by stefanbauer** [comment]
Not sure tbh. I didn't use it anymore until now.

**Comment by calebporzio** [comment]
Closing for now. Re-submit if the issue still persists.
