### ISSUE TITLE
Links do not work if page is revisited

### ISSUE THREAD

**Issue by kurucu** [livewire/livewire#350]
**Describe the bug**
If I navigate away from the page and then head back in the browser, the live functionality stops working. Refreshing the page restores it.

**To Reproduce**
1. Create a page with a component in it that uses e.g. pagination.
2. Use any normal link to navigate forward.
3. Navigate back in the browser.
4. The (e.g.) pagination links no longer work until the page is refreshed.

**Expected behavior**
I would hope that most functionality is restored when the page is revisited, especially while the session is still active.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Safari 13.0.2 (macOS 10.15)

**Additional context**
N/A

**Comment by joseaneto** [comment]
Hi!

The same thing happens to me, checked with Firefox and Chrome.

When you use the “back” or “forward" option of the browser, the "protected" variables are null.

An example:

- A Livewire component receives an Eloquent model that is stored in a protected variable using the mount() function.
- Navigate to a different path and go back or forward with the browser buttons, the value of the "protected" variable set in mount() becomes "null".

We have tried to use the render() and hydrate() to detect when is null and reassign it, but this is not always possible because it depends on the value it receives from the controller.

In our case we are creating an online store, working with components performing the function of a shopping cart, list of products, filters, etc..

Is it a bug or is it the normal behavior we should expect?

Regards!

**Comment by calebporzio** [comment]
Ah shoot, that makes sense. Here's what's happening:

* Visit page
* Component is loaded and mounted with fresh id
* Leave page
* Revisit cached page (hit back button)
* Component with stale id is initialized in JavaScript

Everything works fine in components with only public properties (although the browser doesn't retain any state (it resets to the initial state)). HOWEVER, components with protected properties get messed up.

The problem: protected properties are stored inside the session, and garbage collected after a user leaves a page.

Potential Solutions:
A) Modify the garbage collection to have a longer buffer to prevent more of these issues (the con being that the cache will have more stale data in it, taking up more storage)
B) Modify the garbage collector to only collect when a tab is closed (this is REALLY hard to detect I believe AND would grow the cache even larger)
C) Do some stale component checking on the backend and re-mount the component (but like you said, this is  an  issue because of data passed in from a controller won't be present)
D) Force pages with Livewire components to not be cached in the browser (this seems terrible)

I'm sure there are other answers, but I figured I'd get the conversation started. Ideas anyone?

**Comment by kurucu** [comment]
Is there a clean way to design around it? Or, perhaps provide utilities like `<div wire:stale>`  and `<div:wire:fresh>` to allow for detection in the UI and appropriate commands to be provided.

Alternatively, move temporary storage on the server side from the session to the cache; allow serialisation like laravel queues does with models? [See here.](https://laravel.com/docs/5.8/queues)

**Comment by calebporzio** [comment]
Hey @kurucu, so I have been doing A LOT of thinking about this problem. You can find the solution I've chosen to go with outlined here: https://forum.laravel-livewire.com/t/help-me-solve-the-hardest-problem-in-livewire-and-maybe-the-entire-world/22/32

For now, I'm moving away from the direction of automatically caching things.

I'm still open to feedback on it though, there are no easy solutions as I can see.

Closing for now as this issue will not exist in the latest release of Livewire.

Thanks!

**Comment by sitnikovalex** [comment]
Hello, guys!
I have same issue on Safari.
Nav back in the browser and Livewire no longer work until the page is refreshed.
Livewire 1.0.1
Laravel 6
macOS Catalina
