### ISSUE TITLE
Livewire component as row in table 'TypeError: this.el is null'

### ISSUE THREAD

**Issue by kverstae** [livewire/livewire#368]
**Describe the bug**
When using a livewire component for each row in a table (`<tr>` is the root of the template), interactivity is not working as expected. 
When clicking any of the buttons, you get the error `this.el is null` in the console and elements of the component disappear.
When adding a `<div>` to surround the template, errors are gone, but the buttons have no effect

**To Reproduce**

Quick dummy to showcase the problem:
_**Blade template**_ (test.blade.php):
```
<tr>
    <td>
        <button wire:click="increment">+</button>
    </td>
    <td>
        {{ $count }}
    </td>
    <td>
        <button wire:click="decrement">-</button>
     </td>
</tr>
```
_**Livewire component**_ is just the basic counter example.

_**Main template**_ that includes the livewire component:
```
<table>
    <thead>
        <tr>
            <th>ADD</th>
            <th>VALUE</th>
            <th>SUBSTRACT</th>
        </tr>
    </thead>
    <tbody>
        @for( $i = 1; $i < 4; $i++ )
            @livewire('test')
        @endfor
   </tbody>
</table>
```

**Expected behavior**
Working counter in all rows of the table

**Desktop (please complete the following information):**
Tested on Firefox and Chrome

**Additional context**
Not sure if this is a bug, or just me overlooking something...
Still new to livewire, but I realy like the idea!

**Comment by shadoWalker89** [comment]
I have something like this but instead if using a component I'm using a simple include to another blade file

**Comment by kverstae** [comment]
I don't quite understand what you mean by including another blade template.
I still want it to be dynamic, without using JS in the frontend.

**Comment by 2kodes** [comment]
@kverstae 
maybe you could refer to [this portion of the docs](https://laravel-livewire.com/docs/nesting-components/#keyed-components) and try adding a key to the component as its done...I think using a key will fix your issue

**Comment by shadoWalker89** [comment]
@kverstae Sorry i thought the table it self is a livewire component and each row is a livewire component.

What i meant in my previous comment is that if you are trying to only organize your code then use an @include('row') instead of making it a livewire component @livewire('row') 

But this doesn't apply since in your case you want the row to be a component.
I think you should try what @2kodes said

**Comment by kverstae** [comment]
@2kodes I found this just after posting the issue, but even adding `key()` doesn't solve the issue.

I found some other things, not sure if normal or a part of the problem here.
When using `<tr>` as root element of the object, the rest of the component stays nested within these tags when inspecting source of the page. This means you get something like this, which seems normal.
```
<table>
   <tr wire:id="....">
        tds of first component
    </tr>
   <tr wire:id="...">
        tds of second component
    </tr>
</table>
```
When nesting the whole component in `<div>`, `<form>`, `<span>`... you get something like this when inspecting the code:
```
<table>
    <div wire:id="..."></div>
    <tr>tds of first component</tr>
    <div wire:id="..."></div>
    <tr>tds of second compnetn</tr>
</table>
```
The biggest part of the component is not nested in the root element.
When you use `<table>` as root element, everything works as expected and sourcecode looks like it should? (table with the wire-id surrounding rest of the component)

Is this behaviour normal? I am just making guesses and trying to find the cause of this problem.

**Comment by roni-estein** [comment]
I’m just on my cell in a oarkade checking mail but this popped up. I wanted to verify it’s not key() but wire:key, you can find it by searching for key in closed issues. I think Caleb was changing that in the docs and it may not yet be updated. Hope this helps!   
  
  

  
>

**Comment by kverstae** [comment]
@roni-estein 
Thanks for the tip, but I don't think this is what I need (atleast it doesn't fix the issue, or I am doing something wrong here)
I added the key to the root element, as you would do in vue, and also tried to add the key to the buttons. Am I supposed to put this key somewhere else?

**Comment by kverstae** [comment]
I think this is related to (if not the same as) #36
The issue can be solved by using DIVs, but layout of these is more of a hassle than using TABLE.

This issue can be closed if it is indeed the same as the other issue

**Comment by roni-estein** [comment]
I won’t have time to look at this from an avtual laptop until Monday but if it’s still open and there is a sample project I can clone and look at I’ll give it a go.  

  
  

  
  

  
  
>

**Comment by kverstae** [comment]
So i started creating the sample project but failed to replicate the issues at first.

Upon further inspection, I found that importing Vue was causing the issues. When adding Vue to the project and loading it as described in the livewire docs (`window.Vue = require('vue'))` and issue #67, the `TypeError: this.el is null` returns.

You can clone a sample project from https://github.com/kverstae/livewire-bug-showcase

**Comment by roni-estein** [comment]
I can check it out, but did it work when you didn’t have Vue installed?

**Comment by johnnyfreeman** [comment]
I'm running into this same `this.el is null` issue too. I don't have Vue installed (`window.Vue is undefined`).

In my case it's for a custom multi-select component where options initially load via `Model::all()` and then are replaced by search results from Scout. For me it happens when I select something initially and then try to search.

I've tried:

* not using `wire:key`
* using `wire:key="{{ $loop->index }}"`
* using `wire:key="{{ $model->getKey() }}"`

Is there something else I should try?

**Comment by johnnyfreeman** [comment]
If I jump through the callstack. The issue seems to be here:

```javascript
function closestByAttribute(attribute) {
  return new DOMElement(this.el.closest("[".concat(prefix, "\\:").concat(attribute, "]")));
}
```

In this case it's trying to find the closest ancestor with "wire:id", which is the root component node, and can't for some reason. Although, if I run the same thing in the console, it finds it.

You can test this yourself by clicking on whatever `this.el` references in the code above in the inspector window. Then switch over to console and run:

```javascript
$0.closest("[".concat("wire", "\\:").concat("id", "]"))
```

It would appear that the root component node isn't ready when `closestByAttribute` is called.

@kverstae is this the same thing you are experiencing?

**Comment by kverstae** [comment]
@johnnyfreeman This is not the same thing I am experiencing. My problem was related to a conflict between vue and livewire.

I just fixed this issue by moving the `<div>` where Vue binds on. Originally it was the root element of my complete page. By moving it just around the custom vue component, all issues were resolved.
