### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by skinnydesign** [livewire/livewire#390]
Hey all, 

I have an issue with form validation and wondered if you could help. 

So, I have a master component (form) that loads sub components (inputs) inside of it. The only way that I have been able to get to get validation to work is to create events on each sub component that will run the validation on that component then report back to the master component that it has or hasn't passed validation to display the message and to stop from submitting the form.

Does anyone know of a better way as it does feel really hacky and very tightly coupled to this one form.

I would ideally like to run a submit event on the master that has all the information of the child component inputs and do the validation there.

**Comment by calebporzio** [comment]
I would suggest putting your inputs in Blade components (not livewire components) and keeping everything in one master component so you can easily bind to the data and what not.

Otherwise you have to do some event emision like you're doing to get what you need done.

You could emit an event from the input child called "updateFoo" (assume the input's name is foo) - and listen for that on the master. Then every time foo is updated, run validation or something.

I'm going to close this for now. But feel free to post a code example and a description of the problem on the forum under the "Help" category: https://forum.laravel-livewire.com

Thanks!
