### ISSUE TITLE
Utilize SerializeModels trait from queue component to restore model properties

### ISSUE THREAD

**Issue by driesvints** [livewire/livewire#488]
**Is your feature request related to a problem? Please describe.**
I've only just stumbled upon https://forum.laravel-livewire.com/t/help-me-solve-the-hardest-problem-in-livewire-and-maybe-the-entire-world/22 so this might be a bit late. However, since we're not at 1.0 I believe there's still time to do some changes.

Event though I recognize all of the problems from the thread and share @calebporzio's thoughts that none of the previous solutions were ideal, it still remains a bit unfortunate that we can't set models on properties that are automatically restored. This leaves us with some dirty code imo by needing to use computed properties which weren't exactly meant for this.

I believe we should give this another go and strive for the best DX possible. I sincerely think we can tackle this problem in a good and performant way.

**Describe the solution you'd like**
In an ideal scenario I'd like to set models from the mount method to public and protected properties that are automatically restored. This is exactly the same principle as for serializing and restoring models for queued jobs. Therefor, I believe we can re-use the `SerializeModels` trait for this which is exactly meant for this. We can use it to serialize the identifiers and restore the models when Livewire re-renders a component. The `SerializeModels` can live on the `Component` class so people don't need to implement it themselves.

Note also that this won't serialize the entire model. Just its identifier, classname, any loaded relations (also identifiers/classname) and connection info.

I don't know anything about the Livewire internals or what it would take to implement this so I'm afraid I'm of not much use after this. I'd be willing to give it a go if needed.

Ideally instead of writing this:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Spatie\MediaLibrary\HasMedia\HasMedia;

class ImageUpload extends Component
{
    public string $modelClass;

    public int $modelId;

    public function mount(HasMedia $model)
    {
        $this->modelClass = get_class($model);
        $this->modelId = $model->id;
    }

    public function getModelProperty()
    {
        return $this->modelClass::find($this->modelId);
    }

    ...
}
```

I want to write this:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Spatie\MediaLibrary\HasMedia\HasMedia;

class ImageUpload extends Component
{
    public HasMedia $model;

    public function mount(HasMedia $model)
    {
        $this->model = $model;
    }

    ...
}
```

**Comment by calebporzio** [comment]
I agree with everything you said @driesvints.

My only question remains:

Can we expose that information to the front-end in plain-text? (id, connection name, model class/namespace)?

If the answer is yes, then I love it - let's do it. As you said, DX matters and the current route is too complex.

If the answer is no, do we encrypt that part of the payload (makes the payload bigger by ~x3, and slower). I don't like that solution, but maybe that's what it needs to be.

Also, if we go this route. We will break some behavior of `x-model`. It won't work with this implementation (unless we add more logic on the backend to kinda-work (I think)). It's definitely not a deal-breaker, but it will add more potential edge cases.

**Comment by intellow** [comment]
It's obviously the best developer experience if we can make this work. I personally don't have any concern about making model ids public, as I do that in my routes all the time.

I'm trying to think of a situation where someone could use the connection name and/or model namespace nefariously, and I can't think of anything off the top of my head.

**Comment by boomerstan** [comment]
Why not provide for both? The public model for better DX and a private encrypted model for when privacy is desired?

**Comment by assertchris** [comment]
I think the issue is bigger than just models. Having written a significant amount Livewire code, over the last few months; I enjoyed the freedom to store complex data structures that would never reach the client. That is downright painful to do now, especially with nested components that have their own state and parameterised parent state. 

This is the pattern I've kinda settled on, for one of the apps I'm working on: https://gist.github.com/assertchris/d570feb4a73c30fa1d17082a4e1dbf49

It allows this functionality to work, albeit with 1 or 2 caveats I'm not entirely comfortable with...

![upload-demo](https://user-images.githubusercontent.com/200609/71423403-dee6c300-2691-11ea-93c5-cacc4effd5b6.gif)

1. State is stored in multiple places. I want the nested components (like `SelectRepositories` and `SelectType`) to remember what values they had set between reloads, so I store their state in cache, and remember the cache key in the session. I also want the "container component" to suggest what their initial data was, without the components having set that themselves. This means the nested components state could get out of sync with the same state being sent from the container component.
2. It's so much boilerplate. The components need to know about this JSON/raw distinction. They need to generate their own uuids for cache keys, and set/get their own session data. Why should they know about cache or sessions? 

I think the exposes a problem with the design of Livewire (or at least how I think about it, and ways I expect it to work)...I want to think of the Livewire components are things that continue to live between requests. That might have been the starting-point (in the era of web sockets), before all the state was sent back and forth for each request. Now, they appear to be moving in a direction where they're just a collection of methods on a DTO; where the DTO is populated by Livewire. 

Protected properties felt like the former, and all this boilerplate feels like the latter. I know there are reasons for the change, and other than suggesting the objects do live across requests (like with a daemon) I don't know of another elegant solution.

**Comment by donnysim** [comment]
This might sound stupid and I'm not sure it really fits, but maybe there's a way to play with cookies? like make a specific page cookie as the cache for per page, then no matter when the user gets back it loads the state from cookie (though this could also prove problematic for page refresh etc?).

**Comment by litvinjuan** [comment]
> I'm trying to think of a situation where someone could use the connection name and/or model namespace nefariously, and I can't think of anything off the top of my head.
I think the answer lies here. Can't think of any, but would be nice to get a couple of views on this.

If the answer remains no, I would tackle it as @calebporzio

**Comment by calebporzio** [comment]
Ok, these are all good points.

* I agree that the current solution is bad UX.
* I think auto-serializing models set to public properties is a great solution and I'm also fine with exposing that data to the front-end based on opinions and other tools (Laravel Echo)
* I don't want to auto-store protected properties in a cache. There are too many edge cases and too much to manage. However, I'm fine with offering a `$this->cache()` type API out of the box to manage a per-component-instance cache

Here is my proposal:
1. We add auto-model/collection casting for public properties
2. We add a Livewire-provided `$this->cache()` API (not as high of priority)

@driesvints: thanks for bringing this back up and offering an elegant solution.

@donnysim: not stupid at all. Thought pretty hard about this today, it is definitely a valid solution for a certain set of problems that would crop up if we went back to the old protected properties solution (which I don't want to do).

@boomerstan: yeah, this may end up being desired. The payload size of encrypted data is what always gets me (and the extra processing time to encrypt (well))

@intellow: good to get more opinions on that. Thanks.

@assertchris: thanks for the input, I haven't had the time to dig more deeply on what you shared (I did however skim). Would your needs be satisfied by my prescribed solution (the caching utility out-of-the-box). Would that ease the pain a little bit? How much of the data you're storing HAS to be kept on the backend? Is it mostly for speed/payload size? Or also for visibility reasons?

Thanks again everyone!

**Comment by driesvints** [comment]
>  I'm also fine with exposing that data to the front-end based on opinions and other tools (Laravel Echo)

This is indeed a good remark.

> We add auto-model/collection casting for public properties

All I ever wanted for Christmas ❤️ 

Thanks for all the feedback on this 👍

**Comment by calebporzio** [comment]
Ok, I implemented the "auto-serializing" models thing on `dev-master`.

If someone could try it out and give me the green light, I will tag it.

Something we MUST protect against: a user tampering with the serialized state (changing the id to another id they don't own or something) and it being un-serialized back to a model they don't own.

There are 2 ways I can think a user could do this:
1. Tampering with the component's "data" before sending it in the request payload.
  * We are protected against this because of Livewire's payload checksum.
2. Manipulating the id with something like `wire:model="post.id"`, which would allow them to update the id of the model.
  * I added protection so that Livewire will block any data-binding on these models or model collections. It's a new exception called: `CannotBindDataToEloquenModelException`

I added tests for both of these cases. Of course, if there are any other potential vulnerabilities people can think of, please speak up.

**Comment by assertchris** [comment]
Any chance we could also get an interface for custom classes to implement, that will pass them through the same dehydrate/hydrate process?

**Comment by driesvints** [comment]
@calebporzio it works really well! Thank you so much 👊

**Comment by driesvints** [comment]
About data protection: I believe this should be done by authorization within the component and that this is the developer's responsibility. This is already documented: https://laravel-livewire.com/docs/authorization/

**Comment by mikebronner** [comment]
I'm struggling with this problem, but I don't think it can be solved with relying on serialized models. What I am doing is passing a query builder object to the Livewire component, and then manipulating it in various ways in the component, based on user input. Is there a way I can make this passed-in query persist? I have been wracking my brain against the desk trying to overcome this. Any ideas? Thanks!

**Comment by driesvints** [comment]
@mikebronner no idea I'm afraid.

@calebporzio guess this can be closed then?

**Comment by calebporzio** [comment]
Yeah, closing for now.

@mikebronner, @assertchris just mentioned this on Twitter.

That'd be cool if there was a way to safely and succinctly serialize builder instances. Don't think Laravel supports this right now. Feel free to open a new issue.

Closing this one for now.

**Comment by mikebronner** [comment]
@assertchris @driesvints @calebporzio Thanks, guys! I found a work-around for the time being:

```php
@livewire ("component, ["query" => '( new \\App\\Model)->where('relation_id', {$relationId])"])
```

Then in the livewire class;

```php
public $query;

public mount(array $options) : void
{
    $this->query = $options["query"] ?? "";
}

public function render() : View
{
    eval("\$query = {$this->query};"); // horrible work-around, but only way I could make it work
    // do stuff with $query
    $results = $query->get();
    view("livewire.component")-.with(['results" => $results]);
}
```

**Comment by alamamir** [comment]
> @assertchris @driesvints @calebporzio Thanks, guys! I found a work-around for the time being:
> 
> ```
> @livewire ("component, ["query" => '( new \\App\\Model)->where('relation_id', {$relationId])"])
> ```
> 
> Then in the livewire class;
> 
> ```
> public $query;
> 
> public mount(array $options) : void
> {
>     $this->query = $options["query"] ?? "";
> }
> 
> public function render() : View
> {
>     eval("\$query = {$this->query};"); // horrible work-around, but only way I could make it work
>     // do stuff with $query
>     $results = $query->get();
>     view("livewire.component")->with(['results" => $results]);
> }
> ```

hi mikebronner are you sure it is safe?

**Comment by mikebronner** [comment]
I'm not sure this is still needed with Livewire 2.x. What concerns do you have? Why would it be less safe than any other method Livewire uses?
