### ISSUE TITLE
Cannot use @this blade directive in a nested component

### ISSUE THREAD

**Issue by intellow** [livewire/livewire#527]
I have a nested component, and within that nested component I'm using the `@this` blade directive to have livewire send an update on a javascript event.

Unfortunately `@this` this doesn't work when you update the component because that javascript does not get updated when the component updates. `@this` will always reference the first component.

_In the example below, I understand that I could change the `onclick` to a `wire:click` and it would work. I've just used this to simplify what is a more complex implementation where I cannot do that in my case._

#### Top Component

```php
class TopComponent extends Component
{
    public $currentItem = 'first';

    protected $listeners = ['next' => 'next'];

    public function next()
    {
        $this->currentItem = 'second';
    }
```
    
```html
<div>
    @livewire('nested-component', $currentItem, key($currentItem))
</div>
```

#### Nested Component

```php
class NestedComponent extends Component
{
    public $name = '';
    public $value = 'change_me';

    public function mount($name)
    {
        $this->name = $name;
    }
```
    
```html
<div>
    Component Name: {{$name}}<br/>
    Value: {{$value}}<br/>
    <button onclick="myFunction()">Update Value to "Changed"</button>
    <button wire:click="$emit('next')">Move to Next Component</button>
</div>

<script>
    function myFunction() {
        // This works on the first component but not on the second
        @this.set('value', 'changed');
    }
</script>
```

#### The Issue

When the page loads, `@this.set('value', 'changed')` becomes this`window.livewire.find('original-nested-id-string').set('value', 'changed');`

When the nested component is changed, the new component has a different id, but that javascript remains the same and references 'original-nested-id-string` so the update fails.

Is there a way to update the javascript with the new component ID when a nested component is updated?

**Comment by calebporzio** [comment]
Ah gotcha, so I imagine this is a JS problem. Because you've already defined function in the JS runtime, it's going to always be referenced. When the Livewire component re-loads it WILL replace the old script with the new one, but the browser won't re-evaluate the function definition and just use the old one.

I think in cases like these, it's best to avoid putting a function definition inside the component. Maybe define the function globally, and pass in the current livewire component or id from a template expression.

But ultimately, I think most of the cases for custom JS will be moved into custom-directives to avoid all the problems like these.

**Comment by intellow** [comment]
I'm not sure what you mean by custom-directives to solve this problem. Can you explain a bit more?

**Comment by iAmKevinMcKee** [comment]
I think our pairing session from earlier today would also address this issue.
