### ISSUE TITLE
Property doesn't update on wire:keydown when using wire:model.lazy.

### ISSUE THREAD

**Issue by xxdalexx** [livewire/livewire#528]
Any function called with wire:keydown uses the last updated binding from wire:model.lazy instead of the current when both on the same input.

**Comment by calebporzio** [comment]
please provide a small, simple, code snippet to demo the issue better

**Comment by xxdalexx** [comment]
`<input type="text" class="form-control" wire:model.lazy="tagInput" wire:keydown.enter="addTag()">`

Without digging, I thought that hitting enter was causing the tagInput to not make the round trip at first because whatever the previous value was is what addTag() would process. Now that I rebuilt the component to test it, it seems it is making the round trip, but maybe the method is being called before tagInput is hydrated?

Here's the request params the first time enter is hit after putting Test1 into the input:
![image](https://user-images.githubusercontent.com/8096119/73765897-38d3b180-4743-11ea-870e-b59b19edf412.png)

Change the input to Test2 and hit enter and it processes Test1:
![image](https://user-images.githubusercontent.com/8096119/73766048-76d0d580-4743-11ea-8dec-8b530e45fd0c.png)

Change nothing and hit enter again:
![image](https://user-images.githubusercontent.com/8096119/73766196-af70af00-4743-11ea-8555-b10cb1904a4c.png)

The only thing addTag() is doing is pushing the input to an array, and resigning the tagInput to an empty string. The string doesn't actually go back to blank until you hit enter again without making a change to the input box, so after the 3rd request in this example.

**Comment by apeisa** [comment]
Yep, same problem here. No need for any kind of debounce in that kind of situation. It works great when you use `wire:model.debounce.999999ms` for example, but fails with **`wire:model.lazy`.**

When your use case is **add new item** instead of **search something**, then debouncing on text inputs is just unnecessary load. I thought .lazy would prevent that, but it just doesn't work like I thought it would.

**Comment by GertjanRoke** [comment]
Hello, my advice would to change you’re `wire:keydown.enter` to pass the filled in data from the `$event` it self like the example below:

```
<input type="text" class="form-control" wire:model.lazy="tagInput" wire:keydown.enter="addTag($event.target.value)">
```

**Comment by calebporzio** [comment]
This is a tough one.

adding `.lazy` to `wire:model`, makes Livewire listen for an `change` event instead of an `input` event.

As a rule of thumb, (for text inputs) a `change` event is fired when the element loses focus (blurs)

With that knowledge, here's what's happening:

* The user types into the field (nothing happens because the field is still focused and no change event is fired)
* The user presses "enter"
* Because the field still has focus, no change event is dispatched, so the "wire:model" never gets triggered, BUT the keydown listener does!

The solution:

**Use a form tag and submit listener instead of keydown** (more accessible and semantic anyways):
```html
<form wire:submit.prevent="someAction">
    <input type="text" wire:model.lazy="someProperty">
</form>
```

This will provide you with the same behavior and is smart about handling .lazy property updates at the same time as the submission.

**Comment by xxdalexx** [comment]
@calebporzio I'm not going to disagree with using a form tag being more semantic, but this part is just wrong:

_Because the field still has focus, no change event is dispatched, so the "wire:model" never gets triggered, BUT the keydown listener does!_

The action queue you are building to send to the back has the syncInput payload from wire:model, and callMethod payload from keydown, both correctly in the same stack as you would expect. The issue here is that it's being built in the wrong order (presumably from how javascript handles events), and the back end is handling it in that order instead of ensuring that syncInput's are handled first.
