### ISSUE TITLE
Query string defaults

### ISSUE THREAD

**Issue by sebastiandedeyne** [livewire/livewire#550]
First of all, I'm very happy to see first party query string support land in 0.7! 🎉  

When I'm building datatables, or other filter-ish interfaces, I always add the concept of a *query string default value*. These are values that should never appear in the URL.

For example, a `/posts` page with a datatable with sortable columns and a search filter.

If I search `livewire`, it'll set to `/posts?search=livewire`. If I clear my search, it'll update to `/posts?search=`, I'd rather see `/posts`.

Another one: posts are sorted by `-created_at` by default. I sort the table by created date, and end up on `/posts?sort=created_at`. I click again and the URL is `/posts?sort=-created_at`. The second URL shouldn't exist, since it's the default state.

`?page=1` is another typical example of this.

I generally like to set up these default values to avoid multiple URLs pointing to a page in the same state.

Something like:

```php
protected $updatesQueryString = [
    'search' => ['default' => ''], 
    'page' => ['default' => 1], 
    'sort' => ['default' => 'created_at'],
];
```

(there's probably a better API out there, haven't put too much though into the implementation yet)

Is this all worth it, or is this ridiculous? Would a feature like this fit into Livewire? Or should this be solved in the application level?

**Comment by ryatkins** [comment]
@sebastiandedeyne I like this idea and it seems like it could cover most cases.

I just aded this [feature request](https://github.com/livewire/livewire/issues/552) along the same lines: adding 'page' to track pagination changes in the query string.

I also mention a common issue people have with pagination during a search, you need to reset page back to 1 as your result set has changed.

To expand on your idea, add the ability to register this behavior:

```
protected $updatesQueryString = [
    'search' => ['default' => '', 'resetToPageDefault' => true], 
    'page' => ['default' => 1], 
    'sort' => ['default' => 'created_at'],
];
```

Another options would be its own array:
`protected $updatePropertyResetsPage = ['search'];`

**Comment by harrygulliford** [comment]
@sebastiandedeyne This is something I'd like to see too. Could we check if the current property's value is "default" by comparing it against the same property's value of a new class instance? (Possibly using `ReflectionClass` / `get_object_vars()`).

@ryatkins I ran into the pagination quirk recently too. I like the idea of a seperate `$updatePropertyResetsPagination` property. Adding `resetToPageDefault` into the query string functionality feels a little muddy - they are almost seperate features.

Here was my solution given the current API:

```
function updatingFoo($value)
{
    $this->gotoPage(1);
}
```

**Comment by sebastiandedeyne** [comment]
@ryatkins Good call on the page reset! Also something I need to manually ensure that it will happen.

**Comment by calebporzio** [comment]
@sebastiandedeyne - I like me some clean URL too.

Here are the three options as I see them:
A) Just auto-filter out empty strings
B) Auto-filter out default states
C) Add extra API for specifying which values to exclude from the query string

I like the idea of doing something automatically, but I also think it will cause unintended behavior ESPECIALLY because we can't "mount" a component again to see what the initial prop values are (we could instantiate the class to get the public props, but people often set default prop values in the "mount" method)

I think C is best. Here is my proposal:

`$updatesQueryString = ['foo', 'bar' => ['exceptWhenValueIs' => '']]`
or
`$updatesQueryString = ['foo', 'bar' => ['exceptValue' => '']]`
or
`$updatesQueryString = ['foo', 'bar' => ['except' => '']]`

I like `except` the best I think. It's a little more ambiguous, but it would be easier to remember, and it makes more sense with the context of the property name like:

`$updatesQueryString = ['page' => ['except' => 1]]`;

Reads super well.

I don't like `default` because it doesn't express that the value will be "removed" from the URL. If I say "default" I would assume it would ALWAYS be present in the URL even if there was no value.

Anyhow, good suggestion. I dig.

**Comment by calebporzio** [comment]
This'll be available in the next release (it's in master)
