### ISSUE TITLE
How can I flash data (message) after row insert or update?

### ISSUE THREAD

**Issue by shirazsoft** [livewire/livewire#606]
Hello,
How we can display flash message after insert or update database?

**Comment by xxdalexx** [comment]
Need more details and code examples. Do you have the messages programed already? How are you currently displaying messages?

The short answer is however you display the messages, you need a way to trigger it to reload to read from the session again. But there are other issues to this as well, like making sure that is the next request that gets sent, or the flash won't be there. I built a whole system for messaging, I can post the code if you are looking to livewire your messages.

**Comment by calebporzio** [comment]
Here's how I do it:

(From a Livewire component method)
```php
// Do something like add a row
session()->flash('message', 'something')
```

Then if you have:
```html
@if (session()->has('message'))
  {{ session('message') }}
@endif
```
somewhere in the Livewire view it will pick it up.

Otherwise, you have to redirect after flashing so other parts of the page pick it up.

But like @xxdalexx is alluding to I think, you can devise your own system for messaging using Livewire events possibly.
