### ISSUE TITLE
[Bug] Reset is too destructive - isn't listening to mount() ?

### ISSUE THREAD

**Issue by OwenMelbz** [livewire/livewire#655]
**Describe the bug**
When you run `$this->reset()` it resets to what the public properties are defined as.

However if you need to attach logic to these public properties, then your reset will bypass this and leave them as blanks.

**To Reproduce**

```php
class CreateTask extends Component
{
    public $usersForSelectMenu;

    public function mount()
    {
        $this->usersForSelectMenu = User::all();
    }

}
```

Before hitting reset:

![Screenshot 2020-02-29 at 09 38 22](https://user-images.githubusercontent.com/1094740/75605068-5b08e700-5ad7-11ea-96b5-0461b8c3c898.jpg)

So when you "save" your task and call `$this->reset();` it sets the content of `$this->usersForSelectMenu` gets cleared out completely, so your select menus etc lose all their options.

After hitting reset:

![Screenshot 2020-02-29 at 09 38 39](https://user-images.githubusercontent.com/1094740/75605071-64924f00-5ad7-11ea-9867-2955859cd4a0.jpg)

**Expected behaviour**
When calling `reset()` it should respect the state of the properties set after the `mount` giving users the change for dynamic content.

**Comment by MrWeb** [comment]
I think reset() is the correct behavior.
You should call both to do what you want to do:

`
        $this->reset();
        $this->mount();
`

Reset is just a `reset` to basic state. You may want to perform different things after `reset` other than mount.

**Comment by calebporzio** [comment]
Yeah, you're right that `->reset()` doesn't respect things set in `->mount()`

To do so, I would need to store the "mounted" property state with the component and pass it back and forth to the server, which would increase the payload size and slow down responsiveness.

I've chosen this path intentionally because of that.

If it doesn't fit your needs because of `->mount()`, you can drop down to manually resetting data, or rolling something of your own.

If you think it's a big enough issue, chime in here with your 2 cents.

Going to close this for now though.

Thanks!

**Comment by OwenMelbz** [comment]
If it’s the “expected” behaviour, albeit sometimes undesired, then it might just be worth highlighting it in the docs around the reset() section, then at least people will be clear when using it for the first time how it will act.

Do you feel that’s a suitable stop gap for now?

**Comment by torian257x** [comment]
@calebporzio where can I see the livewire state in the client? i can see the XHR on changes... 
![image](https://user-images.githubusercontent.com/2072058/144622224-6c184fb0-8934-4e8e-ab3a-85aaac700a0d.png)

I dont see where is the state?

At least, have an optin for mount resets
e.g. `use CanMountReset` would be nice
