### ISSUE TITLE
Add component slots

### ISSUE THREAD

**Issue by ejunker** [livewire/livewire#68]
Similarly to how Blade supports components with slots it would be nice if I could do something like:

```
@livewire(‘alert’)
	<strong>Whoops!</strong> Something went wrong!
@endlivewire
```

And of course support for named slots would be nice too. I think this would help by allowing components to be be reused. I am not sure how this would be implemented but I thought I'd create this issue to start some discussion around the idea.

**Comment by calebporzio** [comment]
Yeah, this has crossed my mind. Definitely could be really powerful. But would no doubt be tough to implement. Here are some initial thoughts:

1. I could see the implementation not being "that" bad if these were standard Vue-like slots (not scoped slots). They would be able to access the scope of the parent component, not the child they are displayed in.
2. Adding an optional "@endlivewire" is a bit crazy, not impossible, but requires some crazyiness

**Comment by panda-madness** [comment]
Looking through the Blade compiler source, at least on the surface it seems that most of the code responsible for rendering `@component` tags could be adapted for this feature. Specifically `Illuminate\View\Compilers\Concerns\CompilesComponents` and `Illuminate\View\Concerns\ManagesComponents` traits. I'll experiment a bit with this on the weekend.

**Comment by roni-estein** [comment]
Love @wire

**Comment by jgile** [comment]
this would be extremely valuable.  I have countless times that I would have liked to use this.

should just be another directive, for sure.  two behaviors, two directives.  both as concise as they can be for their specific function.

**Comment by calebporzio** [comment]
Closing this for now. Slots aren't currently on the roadmap.

**Comment by natedunn** [comment]
I got this working, but I am not super stoked about the approach. I basically made a wrapper Laravel component that has a Livewire component nested. But it means that every component that needs slot functionality will require double the files to make it work.

**livewire/input/button.blade.php:**
```
<button>{{ $text }}</button>
```

**components/input/button.blade.php:**
```
<livewire:input.button text="{{ $slot }}" />
```

anywhere.blade.php
```
<x-input.button>
      Slots working
</x-input.button>
```

Normally I would hold out for this feature, but since Caleb has spoken on the issue, this might be viable investment if you definitely needs slots. 😞

**Comment by natedunn** [comment]
I got this working, but I am not super stoked about the approach. I basically made a wrapper Laravel component that has a Livewire component nested. But it means that every component that needs slot functionality will require double the files to make it work.

**livewire/input/button.blade.php:**
```
<button>{{ $text }}</button>
```

**components/input/button.blade.php:**
```
<livewire:input.button text="{{ $slot }}" />
```

anywhere.blade.php
```
<x-input.button>
      Slots working
</x-input.button>
```

Normally I would hold out for this feature, but since Caleb has spoken on the issue, this might be viable investment if you definitely needs slots. 😞

**Comment by panda-madness** [comment]
I was toying around with a DIY livewire clone based on standard Laravel Blade components. I sort of got slots working by using Blade component's ability to return a closure from it's `render` method. I then used that data to cache the initial slot contents, and use that in subsequent Livewire-y renders.

```php
public function render() {
    return function($data) {
        $this->cacheSlots($data);
        return view('...')
    };
}
```
This doesn't makes it so slot contents can't have nested Livewire components (I think? Might be wrong).

Don't know how applicable this would be to Livewire proper, since it doesn't use Blade component rendering, but it might be worth exploring.

**Comment by mrspence** [comment]
+1

**Comment by anthony-brindley** [comment]
+1

**Comment by WesleyVroegh** [comment]
+1

**Comment by andonovn** [comment]
Another work-around, without duplicating files as suggested above:
1. Extract the data that you would normally put into a slot to its own Blade file
2. Accept a prop in the Livewire component (as simple as `public string $customBlade = '';`)
3. Inside the Livewire's blade file conditionally render the extracted Blade file from 1. Eg:
```
@if ($customBlade)
    {!! view($customBlade)->render() !!}
@endif
```

**Comment by titonova** [comment]
Created a very simple package that does that: https://github.com/titonova/x-livewire

You can now do
```
<x-livewire _="alert">
  Alert message
</x-livewire>
```
