### ISSUE TITLE
Question about network request...

### ISSUE THREAD

**Issue by syafiqwahid** [livewire/livewire#801]
why every input we made there must be trigger network request even no need..? like when we re custom form submission where have submit button. my point is the form should be like normal everything will be triggered once submission are made.

**Comment by ninthspace** [comment]
You can add .lazy as a modifier:

https://laravel-livewire.com/docs/properties#lazilly-updating

That said, this doesn't stop triggering changes to input fields that are number, date or time fields.

**Comment by GertjanRoke** [comment]
You could avoid using `wire:model` and just use the `request()` class in the method where you handle the submit.

**Comment by syafiqwahid** [comment]
I do try put request on there. But seem live wire cant recognize it..

**Comment by GertjanRoke** [comment]
@syafiqwahid, it looks like what @ninthspace was saying is the only way I can find also.

I made a simple example for you, but even if you use `wire:model.lazy="..."` it will still do a request but lots less because it's only called on focus out.  
https://github.com/GertjanRoke/livewire-examples/blob/master/app/Http/Livewire/SimpleForm.php

**Comment by lancepioch** [comment]
Thanks for the example Gertjan
