### ISSUE TITLE
Livewire\Exceptions\CorruptComponentPayloadException 

### ISSUE THREAD

**Issue by aglipanci** [livewire/livewire#821]
**Describe the bug**
I get CorruptComponentPayloadException on a complex data structure.

**To Reproduce**
N/A - Please read Additional context

**Expected behavior**
The exception should not be thrown.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Chrome 

**Additional context**
Since I am not sure how you can reproduce this I have done some digging myself. Have a look on this diff file:
https://www.diffchecker.com/Leys8hJI

On the left file is the content of initial-data that the component generates in the HTML. After the component is rendered I check a checkbox that would manipulate the data and immediately I get the exception. 

On the right side of the diff is the data object exactly as it comes on the request, dumped from `SecureHydrationWithChecksum` class on the `hydrate` method before running the checksum and throwing the error.
 
If you can see in line 61 of the diff URL the key `main` has moved in the end causing the checksum to fail as the data is not identical to the one initially generated by the component itself. As far as I understand some kind of sorting happens in the frontend that would change the `main` key position.

I have solved this temporarily by getting rid of the string keys (main and secondary) and using only integer keys instead but I thought.

I really hope you will be able to make sense of my description, due to the nature of the application I cannot share actual data and I have masked some so it looks like nonsense :)

**Comment by lancepioch** [comment]
Can you post minimum source code that replicates the issue?

**Comment by aglipanci** [comment]
@lancepioch I have created a repo with a sample component here: https://github.com/aglipanci/livewire-issue

I hope this helps.

**Comment by GertjanRoke** [comment]
Hello @aglipanci, I don’t know if this is maybe a mistake while creating this little demo repo but you should not pass that `data` key in the `render` method.
It will already exist because it’s a public property.

I don’t know how Livewire handles this but I could see that this could lead to problems.

**Comment by aglipanci** [comment]
@GertjanRoke in my original source code I am not using the same name. However, I can ensure you that even with a different name the issue will happen.

**Comment by GertjanRoke** [comment]
Oke, I didn’t look into that but I will give it a look maybe I can spot something.

**Comment by GertjanRoke** [comment]
@aglipanci I think I understand why this is giving a problem because PHP and Javascript handle arrays with alpha and numeric keys differently. Javascript is making an object from the example below because it doesn't support arrays to have "named" keys, so it will change the key `'123'` into a numeric version instead. That's oke, but Javascript also changes the order because Javascript says well numeric keys are more important in objects then string keys. Don't know why but Javascript is just like this.

So for the example below it will fail because Javascript will reorder it and then `'123'` will be first.
```php
public $array = [
    'foo' => 'bar',
    '123' => 500
]
```

So when you reorder your array so Javascript can understand it and will leave the order alone it will work.
```php
public $array = [
    '123' => 500,
    'foo' => 'bar'
]
```

This also works for your code, so I copied the JSON from the diff link and place the 2 `'main'` keys that are a front of the numeric keys after the numeric keys it all works fine.

But man this was a hard one to find what was going on, hope this clears what you need to do.

**Comment by lancepioch** [comment]
Thanks for the help Gertjan!

**Comment by michaellatham** [comment]
If anyone stumbles across this and the above doesn't solve the issue, the problem for me was I had changed the default Laravel middleware location/namespace for TrimStrings. Livewire excludes the `Illuminate\Foundation\Http\Middleware\TrimStrings` and if it exists `\App\Http\Middleware\TrimStrings::class`

My trim strings was at `App\Http\Shared\Middleware\TrimStrings`, but wasn't required so I removed it.

@calebporzio is it worth adding a custom 'excluded middleware' array in the config file? I know you like to keep the config slim.

**Comment by aberramichael** [comment]
Add wire:id attribute to any dom element that you are creating via loop and make sure it is unique (eg: use index of loop concatenated with some string) see if the problem goes away.

**Comment by Yinci** [comment]
For anyone who stumbles upon this thread, but wasn't able to solve it: 
For me it turned out that rounding a value resulted in `-0.0` (e.g. `round(-0.2)`) and was passed back from JS as `0`. 
`0.0` and `0` are interchangable, however a "negative zero" is not. The added dash caused a different md5 hash.

**Comment by solarsilk** [comment]
Thank you @GertjanRoke!

To add a little more info, I used [ksort](https://www.php.net/manual/en/function.ksort.php) in my mount() function on any array property and it solved the issue for me.

Using `ksort($arrayProperty);` sorts the array in place.

**Comment by ericmp33** [comment]
Thanks @GertjanRoke ([source comment](https://github.com/livewire/livewire/issues/821#issuecomment-615939560)).

In my case i was doing this query:
```
$this->selectedCategoriesPrices = $this->editModel
    ->categories()
    ->pluck('product_categories_product_packs.product_price', 'product_categories.id')
    ->values()
    ->toArray()
;
```
This produces this output:
```
[
    '1' => '3.4',
    '2' => '4.0'
    ...
]
```

The problem was that I was missing the `values()` fn to reset the keys!
```
$this->selectedCategoriesPrices = $this->editModel
    ->categories()
    ->pluck('product_categories_product_packs.product_price', 'product_categories.id')
    ->values() // <- here
    ->toArray()
;
```
So now produces this output:

```
[
    '0' => '3.4',
    '1' => '4.0'
    ...
]
```

The difference is in the keys. Now they start on `0`.

When they started on `1`, I was getting this error:
```
Livewire encountered corrupt data when trying to hydrate the [admin.tables.items-table] component. 
Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
```

Now works just fine (:

Hope this can help someone.

**Comment by ifokkema** [comment]
Adding to the possible causes; I had set a lambda function as a value for a variable in my component. That caused the same issue.
