### ISSUE TITLE
Server sent Events for modern browsers

### ISSUE THREAD

**Issue by coding-sunshine** [livewire/livewire#874]
**Is your feature request related to a problem? Please describe.**
Polling is fine when I am not too worried about server load and if I am fine with near real-time data.  But doesn't serve the purpose always

**Describe the solution you'd like**
I was thinking if an alternative if we can use Server-Sent-Events which is supported in almost all the major browsers, and API is simple too.

**Comment by mblarsen** [comment]
AFAIK server-side events are unidirectional. Wouldn't web-sockets be a more obvious choice? There is  [laravel-websockets](https://docs.beyondco.de/laravel-websockets/) based on [Rachet](http://socketo.me/) which works really well.

If the pusher protocol were to me used as the Livewire transport then the user could also use Laravel Echo "for free" on the side should there be the need.

But you are right that SSE has a simpler API and you could argue that inbound and outbound communication doesn't have to be on the same protocol.

Aside:
- the default payload side as implemented in `laravel-websockets` is 250kb I'm not aware if any max limit(?)
- it may be simpler to get started with a Rachet only POC instead of trying to squeeze Livewire into the pusher protocol.

**Comment by lancepioch** [comment]
Here's one resource: https://github.com/hhxsv5/php-sse#symfony-and-laravel-demo

**Comment by mblarsen** [comment]
I just saw today that the JS code is designed around a drivers pattern. Where the default (and currently only) is http. That’s pretty cool because then it should be possible to swap in a ws driver or sse driver that uses the http driver for sending and implements its own for receiving. Just a thought.

**Comment by calebporzio** [comment]
I'm looking into a pattern like this for the future. Thanks for mentioning it. Going to close this for now.
