### ISSUE TITLE
Array key order is changed in the view

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [livewire/livewire#900]
The order of arrays changes in the view.

Set this public array in the Component:
```
[
  35 => "Airplanes"
  33 => "Cars"
  36 => "Trains"
  34 => "Zebras"
]
```

Then `dd()` the array in the blade and you will see:
```
array:4 [
  33 => "Cars"
  34 => "Zebras"
  35 => "Airplanes"
  36 => "Trains"
]
```

**Comment by Te7a-Houdini** [comment]
@ChrisThompsonTLDR does it affect your app . or what is the case do you need to preserve the same order ?

**Comment by ChrisThompsonTLDR** [comment]
Where a user needs to see a list of options that are alphabetic?

Simple example, a list of US states that have IDs, where WA was the first state entered.  WA would have ID 1, and therefore render first in a dropdown.

**Comment by ManojKiranA** [comment]
for now if you need a fix you can get those data from `public method` instead of getting it from `public property`

**Component Code**

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ArrayOrderCheck extends Component
{
    public $selectFromPublicProperty;

    public $selectFromPublicMethod;

    public $arrayOfCountries = [
        35 => "Airplanes",
        33 => "Cars",
        36 => "Trains",
        34 => "Zebras",
    ];

    public function getListOfVechilesProperty()
    {
        return  [
            35 => "Airplanes",
            33 => "Cars",
            36 => "Trains",
            34 => "Zebras",
        ];
    }

    public function render()
    {
        return view('livewire.array-order-check');
    }
}

```

**View Code**

```
<div>
{!! Form::select('selectFromPublicProperty', $this->listOfVechiles, old('selectFromPublicProperty'), ['wire:model' => 'selectFromPublicProperty']) !!}

{!! Form::select('selectFromPublicMethod', $arrayOfCountries, old('selectFromPublicMethod'), ['wire:model' => 'selectFromPublicMethod']) !!}
</div>
```

**Comment by ManojKiranA** [comment]
https://github.com/livewire/livewire/blob/master/src/Component.php#L151

**Comment by Te7a-Houdini** [comment]
@ManojKiranA thanks for clearing the issue . but i think it's not related to how livewire miss with the order . but it's related to Javascript itself 

for example as you can see here the json object is rearranged


![Screenshot from 2020-05-03 10-03-17](https://user-images.githubusercontent.com/17250137/80909132-2529ee00-8d26-11ea-9050-8f54a1eae985.png)

so since public properties are available to window.livewire and since they will be sent to JS code so they will get reordered.

but in case of computed property it won't be sent to JS code . as it will be called from backend . and this is the only solution for this issue IMO @ChrisThompsonTLDR thanks to @ManojKiranA  suggestion

**Comment by ChrisThompsonTLDR** [comment]
Javascript doesn't impact this issue.  The data coming from the public attribute on the Livewire component class, passed to the Blade, has been manipulated.

This is obviously in preparation for Javascript to accept the same data set.

Regardless, Livewire shouldn't change the order of an array that is keyed with integers.

**Comment by booni3** [comment]
I think this is related to the checksum section in the docs?

https://laravel-livewire.com/docs/troubleshooting

`When Javascript is creating an object it will also reorder the keys, it will place numeric keys before alpha-numeric keys.`

**Comment by calebporzio** [comment]
@ChrisThompsonTLDR, Livewire has to change the order ahead of time because otherwise, you will get an error on the next round-trip because JavaScript will mess with the order and Livewire has no way of knowing that the modification is malicious or not.

Livewire draws a hard line that data can't be messed with without going through `wire:model`.

Also, even if we didn't care, you would lose the proper order after the first request because JavaScript would re-arange the options.

Livewire requests are  stateless and the data lives in the JS runtime, so there is no way (other than workarounds mentioned above) to prevent JS re-ordering.

**Comment by calebporzio** [comment]
I would suggest using non-numeric keys, OR storing the IDs and values as objects:
```php
public $states = [
  ['id' => 34, 'name' => 'Washington'],
  ...
];
```

**Comment by latwelve** [comment]
Sorry if I've misunderstood but would using asort($options) on a select (blade component) be ok when looping over the available options array?

**Comment by ChrisThompsonTLDR** [comment]
@latwelve we ended up having to do sorting in the blade.

```
<?php
asort($styles); // https://github.com/livewire/livewire/issues/900
?>
<form wire:submit.prevent="save">
    <x-form-bs name="name" required livewire/>

    @if(count($styles) > 0)
    <div class="row">
        <div class="col">
            @if($existing_style)
            <x-form-bs name="style_id" :select-options="$styles" placeholder="" livewire required/>
            @else
            <x-form-bs name="style" livewire required/>
            @endif
        </div>
        <div class="form-group col-auto align-self-end">
            <button class="btn btn-secondary mt-4" type="button" wire:click="toggleExisting">New Style</button>
        </div>
    </div>
    @else
    <x-form-bs name="style" livewire required/>
    @endif

    <button type="submit" class="btn btn-primary">Create Roster</button>
</form>
```
