### ISSUE TITLE
Cannot wire:click from <template> tag

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#919]
You cannot do `wire:click` from inside of a `<template></template>`, no event is fired at all.
**Why is this important?** Because you can only do `x-for` inside of a `<template>` tag.

```html
<input name="a" wire:model="a" />

<template x-if="true">
    <button type="button" wire:click="$set('a', 'Hello')">This doesn't works</button>
</template>

<button type="button" wire:click="$set('a', 'Hello')">This works</button>
```

**Comment by jjjrmy** [comment]
```
<template x-for="result in results">
    <button type="button" wire:click="$set('a.{{$input->id}}', 'Anything')" x-text="result.description"></button>
</template>
```

**Comment by devcircus** [comment]
definitely not a solution to this problem, but in the meantime, ```<button type="button" x-on:click="@this.call('methodToSetA', 'Anything')">``` is a workaround.

**Comment by booni3** [comment]
I believe I may be having this same issue, but slightly different. It may or may not be related... comments welcome!

I have a modal that is being activated from a button in a dropdown and am therefore using javascript events to open it.

Usually, I would just have a blade component with a trigger method inside and keep it all in-line and this works fine.  i.e.

```blade
<div x-data="modal()" @close-modal="hide" x-cloak >
  <div @click="trigger()">
    {{ $trigger }}
  </div>
  <div x-show="showing">
    {{-- Modal Content/Overlay etc. --}}
  </div>
</div>
```

But now we have:

```blade
<div x-data="modal()" @show-my-modal="show" @close-modal="hide" x-cloak >
  <div x-show="showing">
    {{-- Modal Content/Overlay etc. --}}
  </div>
</div>
```

along with:

```
<button @click="$dispatch('show-my-modal')">Approve</button>
```

Using this second method, the modal open/close seems to work OK but afterwards, we loose "connection" to certain elements on the page with the wire:click attribute. Specifically, it seems to happen to existing elements that are moving position on-page or having elements change around them.
 
I can provide more details if this seems to be something related, else ill dig into it a bit deeper.

**Comment by calebporzio** [comment]
@booni3, I can't speak to your issue, it seems a bit unrelated because it's using `x-show`. Maybe re-post a more complete issue.

@jjjrmy, I suppose this makes sense. Alpine uses mutation observer to react to DOM changes, but Livewire does NOT, because usually IT'S the one making the DOM changes.

This is an unfortunate side-effect of templating inside of Alpine. x-for is unique inside Alpine because it (and x-if) are the only directives that actually drive out entire templates.

My first response would be: See if you can use @foreach in blade instead of the Alpine x-for.

Second, I would use the workaround @devcircus mentioned - that's what I would do.

Third, maybe this is something to look into down the road (using mutation observer within Livewire to react to newly added DOM elements from Alpine).

There's probably other hacky things you could do to make this work, but I think the above mentioned solution is pretty good.

Thanks!

**Comment by Hrituraj202** [comment]
I did a little trick that served my purpose..
From inside the <template>tag I fired a click event to some method in javascript and from there I fired a livewire event.

Firing the click event
`<template x-for="(date, dateIndex) in no_of_days" :key="dateIndex">
    <div 
        @click="fetchData(date)"
        x-text="date" 
    </div>
</template>` 

Firing the livewire event
`    fetchData(date){
      window.livewire.emit('showTodaysData',{ date : date });
    },`

Listening for the event and fetching the data
`
protected $listeners = ['showTodaysData'];

public function showTodaysData($payload){
dd($payload['date']);
}
`

**Comment by victoriopui** [comment]
this would also do the trick x-on:click="$wire.set('property', value)"
