### ISSUE TITLE
Webpack Code Splitting with Livewire

### ISSUE THREAD

**Issue by jgile** [livewire/livewire#974]
When using Webpack code splitting, chunks are frequently loaded immediately after Livewire is initiated, so Livewire directives are not initiated.  I understand why, but don't have a great solution.  Is there a "right" way I should be handling this that I'm unaware of?

**To Reproduce**
1. Setup webpack with code splitting.
2. Load a page that will load chunks that contain livewire directives.

**Comment by calebporzio** [comment]
Sorry jgile, what would you be using code splitting for with webpack and Livewire?

I'll just say here that Livewire is not meant to be used in the context of something like webpack with code-splitting. It's a backend-driven framework, so code-splitting doesn't really fit the context.

If I'm wrong, re-submit the issue with an example repository that I can browse. Otherwise, I would recommend sticking to the advised approaches in the docs.

Thanks!
