### ISSUE TITLE
wire:loading - Image support?

### ISSUE THREAD

**Issue by myriadcode** [livewire/livewire#978]
Hi there,

I'm using `wire:loading` to show a placeholder. The data fetched contains images which are then embedded onto the page.

Whilst the placeholder shows during the initial fetching of data, while images get loaded it disappears. This creates an empty state where the `wire:loading` disappears and there is blank space until the images are loaded.

My question: **Is it possible to keep wire:loading active until the elements fetched are displayed/loaded?**

**Comment by DanHarrin** [comment]
Hey. Maybe try using a `wire:loading.class` to toggle the placeholder's visibility instead of loading it each time with `wire:loading`?

If this doesn't work out for you, please use the [Discussions section](https://github.com/livewire/livewire/discussions), where we can consider alternative solutions. Many thanks!
